apiVersion: v1
kind: Secret
metadata:
    name: anubis-key
    namespace: forgejo
stringData:
    ED25519_PRIVATE_KEY_HEX: ENC[AES256_GCM,data:Bok345AhOJ9XWNiowu2XIGzU3NBiNMKX0H0exN7dozfXW4C/Yu7ACVtFo6NhWbwAVc9M+ozaDxJzlx5J2U1SvA==,iv:BCNQOVORscoL+4k0+hIDEZeVGPLXAgU9hpzwxB/2QVA=,tag:67MhP4YRsGphORiFGpX4QA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjeE1YUEQxbUx6aCtqODc3
            K1RJaElDMTlraEZlK0toemNvQmltNFBnYjJvCmVvNTVwcFdNWG9EanpYdFhWWm05
            RmxnWUt2TWw3MjJxN3UzcVVhc0tyWVEKLS0tIG9UY1BXZzdpdGNHYUQ3VGJHOVV3
            OEs4WHVUVFZVSUM0czZGWklhZVQzNlEKyyHyc6+sxzXXjLaW7T1y686jHR32mQHg
            dMnd83t609TGKQKuywq6FUtao9sVncH+RfthTzDv7rjqDs+guSmZnw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jk99rtxq3ep2xj2w886cchddf7jypqpwkr3dszg5dzq93gn8cy9qyc786m
    lastmodified: "2026-10-04T19:59:24Z"
    mac: ENC[AES256_GCM,data:/rmBvSa+yj2PieUoK4elchdYp68b2gsPGm+HAeBzy1uuln6VlG3VsGqxR5K1TAzsEJpFpNILVUoMb9pFEpmJfXi7NivHa9++RLjeaHSTl8fnp1epI6byYyzWHk6HA4Fl2MsSTV5/MhCIqAqqm5Mxgv9PUIVxFrhcdHhJcWIPW8g=,iv:jzxY3P58q7cAIoVS92m++4c6N94aoBcptNBPXcBsVtQ=,tag:OEpn+ZPSNUpOcLEI5c0aFQ==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.13.3
