apiVersion: k8up.io/v1
kind: Backup
metadata:
  name: forgejo-backup-test
  namespace: forgejo
spec:
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 1
  backend:
    repoPasswordSecretRef:
      name: forgejo-backup-repo
      key: RESTIC_PASSWORD
    s3:
      endpoint: "${BACKUP_S3_ENDPOINT}"
      bucket: "${BACKUP_S3_BUCKET}"
      accessKeyIDSecretRef:
        name: forgejo-backup-repo
        key: AWS_ACCESS_KEY_ID
      secretAccessKeySecretRef:
        name: forgejo-backup-repo
        key: AWS_SECRET_ACCESS_KEY
  podSecurityContext:
    runAsUser: 0