apiVersion: v1
kind: Secret
metadata:
    name: forgejo-db-credentials
    namespace: forgejo
stringData:
    username: ENC[AES256_GCM,data:CRXFHyUeZA==,iv:Tq9O5HK3XvlFV89r9s+dF/usht+N0qqsdeyHEvLE27k=,tag:hO/VRlrxEbHLUkzQ9kbshA==,type:str]
    password: ENC[AES256_GCM,data:1SkkVNQYGg==,iv:RttyoEiMtVwU8/IyCh43rS7q4jl4A0aYJEoNmM5Vm6s=,tag:VTO79FlMLjQIWe3/p0ha3Q==,type:str]
sops:
    age:
        - recipient: age1jk99rtxq3ep2xj2w886cchddf7jypqpwkr3dszg5dzq93gn8cy9qyc786m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUcjNnbkd5T0lZdkZOQXYz
            U3VZYzVyaHhEOGFrQ2hhMUlaVG5KZ1Z0elEwCitCN283UVhRN0g1d1ZyTXVNNHp3
            QThXRWwxbGhrSlJrVEhJbko0WmppWHMKLS0tIDMrYXhJY1dUVzNYSUNMZDZ3TTBG
            Y0s4MzVMdDBUYTUwODFMb3Z1cVg2UFUKpesUGlGuNqIXI+HB+AfJ3g+534CbRNwT
            HRIhX3mID1cCKcInq6yUDGGT2rgRCz/2UYyUg4h7DfoY3BmcRj2hog==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-18T18:46:11Z"
    mac: ENC[AES256_GCM,data:0dlIPB4wlh9LKW9crZQHaA8ohBNHRgkW9CKBkynK6VkMuB8u909F58aAl3riYQ0FMfkkk7EyIdjLCeS0psxTbnOJphmN0a+XFsO163E67+Ifv3QBzI6bZQYR7NDP1e8GrnG+mxP0n6HlqWzKFno+XhOzgN3nTn0MOBP4xQSwzOg=,iv:O0ZjNW8izvzbczaiD9OSThHmmcpsuGTXIsGIbHO0xCY=,tag:ZKtptKPWO9lVf8NoI6wUJw==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.11.0
