apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: forgejo-db
  namespace: forgejo
spec:
  instances: 1
  bootstrap:
    initdb:
      database: forgejo
      owner: forgejo
      secret:
        name: forgejo-db-credentials
  inheritedMetadata:
    annotations:
      k8up.io/backup: "true"
      k8up.io/backupcommand: sh -c 'pg_dumpall --clean -U postgres'
      k8up.io/file-extension: .sql
  storage:
    storageClass: retain-local-path
    size: 1Gi
