# /apps/prod/forgejo/release.yaml
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: forgejo
  namespace: forgejo
spec:
  interval: 1h
  chart:
    spec:
      chart: forgejo
      version: 11.0.3
      sourceRef:
        kind: HelmRepository
        name: forgejo
        namespace: forgejo
      interval: 1h
  valuesFrom:
    - kind: ConfigMap
      name: forgejo-prod-values