apiVersion: tailscale.com/v1alpha1
kind: ProxyClass
metadata:
  name: host-network
  namespace: tailscale
spec:
  statefulSet:
    spec:
      template:
        spec:
          hostNetwork: true
          dnsPolicy: ClusterFirstWithHostNet
