# /apps/base/lemma/pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lemma-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: retain-local-path
  resources:
    requests:
      storage: 10Gi