# /apps/base/headlamp/repository.yaml
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: headlamp
  namespace: headlamp
spec:
  interval: 24h
  url: https://kubernetes-sigs.github.io/headlamp/
