apiVersion: v1
kind: Secret
metadata:
    name: cluster-vars-prod
    namespace: flux-system
stringData:
    #ENC[AES256_GCM,data:7mJocqIeGv+5Y+TiPq1fsA==,iv:Tb/MExSa5qhQbl2i9AkoBRwvjDQ51eTx2R1mA1uTvZY=,tag:uKvcqwL2dzrzjW5b9/4p3Q==,type:comment]
    MAIN_DOMAIN: ENC[AES256_GCM,data:0S4cfs5DgjgS,iv:mbhzNPNNHrt4vRVxRX+kVKtz/lGgUyXt6LAKxAruqcY=,tag:83SEVC+kQrA87/95W1SmgQ==,type:str]
    SECONDARY_DOMAIN: ENC[AES256_GCM,data:DLFpdpulNJznDY2TMEtIUA==,iv:BNxi7PVfJOGnsZRG1ldZPashCggms4/2RqTFGcKHu5I=,tag:9nV4jAruvnXwgz9n4MJT0Q==,type:str]
    #ENC[AES256_GCM,data:YbSR0fScoQyx08LXF5SW+g==,iv:+Xxur6DRqZ3xF9Yctx4oQomay+Uxu6IU6n4mjZIueBI=,tag:diVdjcuUzA5VnxrYC3Biqg==,type:comment]
    FORGEJO_DOMAIN: ENC[AES256_GCM,data:F16hpedZ8aKSGfmZIw==,iv:cAMVqCfYvX7GOBBXnhiIRovFjSP2z3lrXk7/oKJlcPM=,tag:sZ8x2fD/EjV0fZK4wzJeyg==,type:str]
    AUTHELIA_DOMAIN: ENC[AES256_GCM,data:00TWdr/jCRJKIm1uIc8=,iv:v5yALObK6Is70o9HFR+g+UummnzuQmzUE1PpA3/DfiQ=,tag:za38nbAj9ny0oqvl0twD5A==,type:str]
    TRAEFIK_DOMAIN: ENC[AES256_GCM,data:/V4bKC4Js3MfamqueYXWCbA=,iv:zoO71497ai9GCNzAuLIp+Fa17bnB0g2l2KETBYaYRMs=,tag:n2428jiK8GJPMkuM5xsPoQ==,type:str]
    LEMMA_DOMAIN: ENC[AES256_GCM,data:2gkHev/ljzsAI4/NUSxs,iv:ReWGHSzhwxQeDksacG0t0cN0h54RIOnjaQt8a8XxTcU=,tag:ls2A8iMcgCu0QqOMrXCr4w==,type:str]
    K9S_WEB_DOMAIN: ENC[AES256_GCM,data:T5WeeRFBQp/vkywH/A==,iv:/20btius49i6Jdj7ZGVvM9L24donP1uduQ/zSo6YORk=,tag:JNlUXHvpv4hdGWukFz1K9g==,type:str]
    LUTE_DOMAIN: ENC[AES256_GCM,data:pngiTeRCOjgDGDLOwXQ=,iv:kaQ3nStuvlGbgeU+7md24wsKELuMJB1tX6A59rkUOgQ=,tag:p5ZFxqe/qrww5YbBeJSTxg==,type:str]
    VIKUNJA_DOMAIN: ENC[AES256_GCM,data:AfyF60zJgHTwTBoVL/p9,iv:KCv7Tta9pcPnEsbXdzEbQpHnbdHq4zz4wKBhQOCzoug=,tag:B+Yv23iftWlrukiMarhk8A==,type:str]
    #ENC[AES256_GCM,data:tbj9ycVkewBwWbiWyi9z8IPQu8E=,iv:2+KZaqihYAER8P9sHs4eenabv8MmNnZuTOaXZXLqRC0=,tag:MeYmhV8B2DijlzJUuVWmEQ==,type:comment]
    LETSENCRYPT_EMAIL: ENC[AES256_GCM,data:/rhMA5Z8K8t1llaRY1B/JAKsrEisUME=,iv:w8r8mn2J50KspFXWoaGUK3mCwDx5Ec8GsFpzq9W2QOU=,tag:UTSFBO3Xd2UxgfTGkz641w==,type:str]
    FORGEJO_ADMIN_EMAIL: ENC[AES256_GCM,data:JhTDIIIosLfUzOy4pLYYu14=,iv:RS/1YNEut3yc+YHn98h4eg5wPHxaBRvCGTqFMf9Guvw=,tag:n/Sxkn+tRnSyEhF6V7cGTQ==,type:str]
    GHOST_ADMIN_EMAIL: ENC[AES256_GCM,data:vSa6rbBNrKh936zsGX9/JVc=,iv:g1W4J1lnmehsL/v6rWq2qucVf2xz9bfA1V63ue6lhtE=,tag:pyJzVddLXLwiClWZCEZysw==,type:str]
    #ENC[AES256_GCM,data:KBoTdGJ3RKRsd1SIhdJWnrczfy8sQa5oYoZAeg==,iv:DcCz6cmjoIfktuAy/tCajRMYLM82UcUaHdL0lYtIMRg=,tag:Qm2FQzc1qDICtJisvwd7bw==,type:comment]
    HOMELAB_DOMAIN: ENC[AES256_GCM,data:OmahMbKuj40LCrX04A==,iv:CU9ekuyqikZCZ6KdcpFabCLs++tKwCjqtub6rbBiwYc=,tag:/KRbu+9htVl+hDdnD5qo/w==,type:str]
    HOMELAB_TAILNET_FQDN: ENC[AES256_GCM,data:hm7do6WVs07q7PKYcOt+nDGXO7i27wJEzE/+We0=,iv:Z0LyMK/tbxCjF1jPgisyI2MAVcDv/YT5kciigl0hBlA=,tag:uWtGGWdgC8QLbRWek8nc4A==,type:str]
    HOMELAB_INTERNAL_PORT: ENC[AES256_GCM,data:SsyEfA==,iv:9+DIWnJv0/rlMyP+pEZzrD/2bpfMXJoF7iF+TdYNhhM=,tag:n2Emrx50fcXkCJLJHSCSxw==,type:str]
    HOMELAB_ANKI_PORT: ENC[AES256_GCM,data:jim48A==,iv:xilqJ5T4J009rN2Y5U85byvTIzQQa13dfdEWMqIX2Jw=,tag:cuoEDDhmMZHCcnQW2FTSiA==,type:str]
    #ENC[AES256_GCM,data:GAmIztHw/w5VxXqHIRHZRhDu2xV9hvkM,iv:rhlccDlUgOwEcWtafkHEcYl9gmW4crmwk1adYh/x+qU=,tag:sEZNJH3ZuuQ8JU0Yzqtcug==,type:comment]
    BACKUP_S3_ENDPOINT: ENC[AES256_GCM,data:p7C/Jr4HVWdjD3IYmr2SM7tJ9ZsZjDXGYfCm,iv:KmKxgyzK6Tqy1KlgvtsVd9dPtaz+FmfLKPHexcXeW/4=,tag:sH4xrKxFRKG/w01kzH/tDw==,type:str]
    BACKUP_S3_BUCKET: ENC[AES256_GCM,data:D+A4qUcqQYtpBHJfYGQ=,iv:GahRoorqOEQvg8WFzmBqsB+CaHcLiRyJR+V5iR1Y4J0=,tag:DevZlW1Ighb50QMaSN6O+Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBScDN2TW1ta3plSmZiNHNw
            TG5XTGVXdEh0bFdyVnlOR0pzQU5zUWRLQXpjCnAvUWtYWTNHVHFWZHFkT0w0d0VH
            QVFsa0UvVHdYdG9zOExoWE85Z0JyaDAKLS0tIDdoZGxNY2Y4R3lmU0hka1loSk9a
            elRxOU1qRG10NzlCQmNLUHlhbUZmb2MK11E3qW6hZs3qcHWRAn2Geer7jLuDW+gk
            w1DNG5PXNgz4hr4FxgofK4w+PVkkiGGJiaKXT833i/+bNafrULluJg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jk99rtxq3ep2xj2w886cchddf7jypqpwkr3dszg5dzq93gn8cy9qyc786m
    lastmodified: "2026-09-14T19:42:41Z"
    mac: ENC[AES256_GCM,data:RvDjok/pcSKQPpPKpSXjQxN73nbkzbHPPbt8GeqLl0iFzhj+z1CZzDS1/QoI5ed3xYdojbBWhWlVvHNLQPKaENlYPiyIESuLGRtLgtj+M2JsRU5FCv5RNemAmLVt/eq1SrqFNnsGfEDRxD63s6q0uOZnJxkbr/fwbFXid16rFV4=,iv:/pZ6MjjpsGjpCunhwnq7lbT1dVhVfp73bHuq8spD5sQ=,tag:zR010tjCYO8iy8MgXDtyRg==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.13.3
