apiVersion: v1
kind: Secret
metadata:
    name: cluster-vars-prod
    namespace: flux-system
stringData:
    DOMAIN: ENC[AES256_GCM,data:hByh9FaUl7/O,iv:6t1ffAIfjtEOFazJLl/Z6CV+m/XYIwZmvkifzcTdZSA=,tag:ed8Ya+MbdFylYlaN9zmspw==,type:str]
    DOMAIN2: ENC[AES256_GCM,data:jKNLvvWjL0crLQ==,iv:C6dxML68X4F+NZ+XWX0P+93XUO3Y5gyboNDiX6+8OwM=,tag:Ck2mnCZXKlnicRJuuX7vZg==,type:str]
    GITEA_DOMAIN: ENC[AES256_GCM,data:h/c+AoLVU4YF6jhjfQ==,iv:069auYUU4/02rwzanZ4a6NjT8wLtiomgf99fy8EKxdM=,tag:s+ucBGonm09YMCgtzfN1TA==,type:str]
    AUTHELIA_DOMAIN: ENC[AES256_GCM,data:zNrUMFcRycNGx6yn6HI=,iv:lulV5b06SzarEpdqFpCBkD7RUwjCKu6Xl5WZ/3omM9A=,tag:hqEI8I+0yhxdXvuj87bqBA==,type:str]
    TRAEFIK_DOMAIN: ENC[AES256_GCM,data:+ZZIUlkI0y1kp1vjgxTJdpc=,iv:xFU0CApWQJVXFwxWOrnrHoMBDiebwxIaNw4pMk/0mg0=,tag:4NWEuSjTz4GLAw2e7imEIQ==,type:str]
    LEMMA_DOMAIN: ENC[AES256_GCM,data:E9Ca6TKCEC/8tIwMALhB,iv:6XzbMS3mwQPLWo0bzz4jfT9TKsndqJsOAI1zePKq3gQ=,tag:JWyF8Vlh9EJn6C/2ENQ4og==,type:str]
    GHOST_DOMAIN: ENC[AES256_GCM,data:Jjxz44sjjzKT13C+DJVGjg==,iv:NAjMkxD4vKzgL3tR96PS7tZuhVEGIROO8JAg2F52Yv0=,tag:B7Of55BFt2Bv+al74lyC+Q==,type:str]
    K8S_DASHBOARD_DOMAIN: ENC[AES256_GCM,data:wqnr7CoBAel+eYFNUg==,iv:zKCIqAgfRS4ZCKtU4Gte4QcujlygR2z9QEuZhnuYMFk=,tag:o2Rlc5sYjXfNz9M2g9EMmg==,type:str]
    LETSENCRYPT_EMAIL: ENC[AES256_GCM,data:iTeIQ/EhY2TwH+dAwvZir3TMZaHtb8g=,iv:eE2iwYO3b+V1xlbbSOr5gS+lP9meOq6s0916qgFjJHQ=,tag:nc4c/JL9DruDDj+kj0/TWg==,type:str]
    GITEA_ADMIN_EMAIL: ENC[AES256_GCM,data:YQe6qkqu0J/VXaq8ff2Eaf0=,iv:CBsAS9Iwvsh80HAK41WprM26nEvN6GUotcLBrGRXHko=,tag:hmJ5bGNFDB+qfc0UOrLnAw==,type:str]
    GHOST_ADMIN_EMAIL: ENC[AES256_GCM,data:5G8CLASYsd2hOSQLtWfo+z8=,iv:b3Ku5oXxqBk3yPdul0WQCc61IG0Vkv9wmq6zu0C0F+M=,tag:mPGBqGfBQUdjXoo/dxUSow==,type:str]
sops:
    age:
        - recipient: age1jk99rtxq3ep2xj2w886cchddf7jypqpwkr3dszg5dzq93gn8cy9qyc786m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5MGdOcC96c1lTRkcreExZ
            WkNTTmUrTkZjeXk3azJJQzJ6U2FyTEdlb0ZrCkhuL1VhUXJLYjJGWld3dE41aXRr
            MXZ6bGRzY0V4ZjBVaWFSdG83Q01RTEUKLS0tIHpLTTZ6Mk03RExGaUJqejlkai9S
            b0t0UkVkKzZUQUNGcVhYZlBhVG96RE0KPlLg5voWGR99kDA/rK174RxshYkCFeV8
            lkNgdv3KQWy2BgVfkk9IbxRKjIDYKCS79d2lsyAtnCN/H2LFshB/Fg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-14T19:54:02Z"
    mac: ENC[AES256_GCM,data:/oGIJAb+suk+xTcTaRDbJCjwBH6W3Ed7N8p8Z4tCgYwvC0PoU9FTUYeWCIez0JZYM1i/duGWU+ldbGS/SJO1r3Q9ijlNQg27VwY2yU6Y142B0i41N44CCg7m1PscLHnIE07f8bvldfjO19YcxbaLmKcdVNzxqZfNT+2F1SiF8dQ=,iv:7pQuXKKStFvKEvd6X/Mo5kO35nUZYv9/1qIFY0/6ePw=,tag:eHxjWO1u4Uuclb90Pxqjig==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.10.2
