apiVersion: v1
kind: Secret
metadata:
    name: cluster-vars-prod
    namespace: flux-system
stringData:
    DOMAIN: ENC[AES256_GCM,data:F5I4/i5CBIFY,iv:kLcjtpyP1Oe3VJKguhlPD1eTOf989IynVWBTsr0KlQA=,tag:5faKXjFiSXQJnf6cEZG+RQ==,type:str]
    DOMAIN2: ENC[AES256_GCM,data:uppAjEaD5orHuA==,iv:n93YNxjreexK3+mtEl+NyKxFNq6+B52Ola1z6gMNTb8=,tag:DpKSrf+RpfCOHI+WcIG+dA==,type:str]
    GITEA_DOMAIN: ENC[AES256_GCM,data:ZaMGK0y8de8yJVV7LA==,iv:fwpfsjwxwX62xfCDDatg68RFnCCwkhEwKELZhGe7QAQ=,tag:L33jAv93SPaUgNSraN3L7Q==,type:str]
    AUTHELIA_DOMAIN: ENC[AES256_GCM,data:o6Va1c2AzDw/alpz3BM=,iv:16+45Qf1G0bVzlZbu6Rmhipxq/LMXCNCeVU4azg1e4w=,tag:2v5EgfmOhgRTXx2wtujYMg==,type:str]
    TRAEFIK_DOMAIN: ENC[AES256_GCM,data:wsCJ8/4ykY+Ikdm6YYo1BwY=,iv:ksoig3LOp2rpKCkAPOeTvuncZLsn3I0Uz5bQpeXuaBE=,tag:HPa3aHpSTu/lIVq32Gfh9Q==,type:str]
    LEMMA_DOMAIN: ENC[AES256_GCM,data:kKMDB+hTIRO3BDBSm3si,iv:H+w2usI6WhMfYHg3HMysRUQMsPDb/t1v05hZpMX+ZEI=,tag:qOtT3VHW65yj8uzFLcLedw==,type:str]
    GHOST_DOMAIN: ENC[AES256_GCM,data:MWFNSWb0JPRb/IsYXFiSmw==,iv:OBbvUkdl9FieQ7hR5S3CfRhidhar+sdgSAt2C9J+di8=,tag:ggCESRLOGwyIQ35U2NvaKg==,type:str]
    K8S_DASHBOARD_DOMAIN: ENC[AES256_GCM,data:YnTczrMV4mVt3aNxGg==,iv:DyiJTWLHJGbDhODauSsJUB+HEPjqebRQ/DCoOncpow0=,tag:NOD78zxdBhcrS+yC9tpWng==,type:str]
    LETSENCRYPT_EMAIL: ENC[AES256_GCM,data:mEPcyTaKzcm9vH2fai0zPianh9JzOhw=,iv:q6bcTWyWKGZMpj/1R/O/jfRhijvRzYt9+B8EgJJMrvg=,tag:5SRuQYmDCARXCAZVCHq+QQ==,type:str]
    GITEA_ADMIN_EMAIL: ENC[AES256_GCM,data:+DhiTZREwHVeZ938bH2mpcU=,iv:hFKUv+IpV/E10mDYsrgAeaWko7KojJaCTiA6ElJHlg0=,tag:McyU/F9uFzI/XXEF8h+OoQ==,type:str]
    GHOST_ADMIN_EMAIL: ENC[AES256_GCM,data:+8wJ86UCUTQwOhaXABxQWAA=,iv:WPxsPyn3BfqIWlmONWiErN0T6lM76TbU/yMlcNOwjyk=,tag:Ryzx+BeQjL7yz8xuhqKOdw==,type:str]
    LLAMACTL_DOMAIN: ENC[AES256_GCM,data:mA7wjyvwdbvG6bwVxFhni+ZX,iv:WOABZBxZAqjtq19hX4hrFsUnkWBEHSb7VC96ja/eFho=,tag:rWl7Uy2rdJ8VIIkp48I89A==,type:str]
    LLAMACTL_TAILNET_FQDN: ENC[AES256_GCM,data:yrO30vZ4m0PbapDfZfYKsPOuH8AW8j6Eo1arWjk=,iv:XORKCxmMMj5VzlfpjVh7a+e6ylq3kwdrEjt+0YM9UHs=,tag:ALYXRPuoEH68vjTRxQpeNw==,type:str]
    LLAMACTL_INTERNAL_PORT: ENC[AES256_GCM,data:wmyG4A==,iv:d3T5J0kXL58oLdQFFnju3kpddbCuSdBxUK9TGesMkTo=,tag:XVPE5BjpT87eQc42CzMDvg==,type:str]
    CHATUI_DOMAIN: ENC[AES256_GCM,data:N0137+/BldXgZgFY1Vk=,iv:+JvLqcsJYHmpdh931ozQJw/it5X/kn1ffZH40OoashI=,tag:aoK230kVeMY1+QVLROVBAA==,type:str]
    CHATUI_TAILNET_FQDN: ENC[AES256_GCM,data:eTXrtIEgkfuuiifCdntrvCofCDVMjT2/qXuvfSM=,iv:8YQPVqxw3PsFqNzHDp5JSFCf4Wb6nYiNGMxYtIfcPqg=,tag:sIvQIz35VGljvscOVMfcqg==,type:str]
    CHATUI_INTERNAL_PORT: ENC[AES256_GCM,data:L6lZKQ==,iv:ScWMlDv1XeVYiaHghv4TysLMApPtUjx9DqNl9GJ/0g4=,tag:cId8v5+C8UvNqu1H5xZ1Sw==,type:str]
sops:
    age:
        - recipient: age1jk99rtxq3ep2xj2w886cchddf7jypqpwkr3dszg5dzq93gn8cy9qyc786m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1ZTRta2ZYcmZ4ZjB5R0c0
            cEthZnlBQU1SbHFyL25UZmVBeE5lQzE0U1J3Cm5GSlQ3TGYxZ3VWVE0rc2xDd0F5
            REI2VHNkZGdlbUJUMTlQQjBVRHdxQTQKLS0tIEthajZQbGRRVWNYS2ZUVDRTa0xq
            QVZhVnNzanNNeFBhQ0o4ODRJZmpaaG8KAxH3jmNwSsrfCsfIsGSWfdzfxsinnoN0
            p/QrAAm7NijAE5ivOAG7QjNgm0g7AeXWLMgcqLM7R/qtBZ2HMMmEfA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-31T20:31:23Z"
    mac: ENC[AES256_GCM,data:C8ykDHxyobBTIWmzgJvAeFkbst4XGIB+U3V8cVfsaGtdri0EbZsNbIhyLFb3rWJsH04rFwkA+U6pdRA55jyqSUqd1KzL+9IojEct/sEB90BZWwXg/Cl3ufj6xjlOlAvnoRXDy46lC4LhFHjh/UVhmpRFm4mCrsnRZAWPgBMlYt8=,iv:8H3TzwYQbAHSG20vyzEn702niUy2YXS9L+eg2Mcb2hw=,tag:Fwda6wRJcZTPUGjd7KEvYw==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.10.2
