apiVersion: v1
kind: Secret
metadata:
    name: cluster-vars-prod
    namespace: flux-system
stringData:
    DOMAIN: ENC[AES256_GCM,data:HSPGkq2seXIt,iv:Cm/FH+ycG8iIKO4iOJ7/1H+LbUqpPjXeKhq5dFX4hfI=,tag:Jeh7mIxXi+7fK9WFEFoKVA==,type:str]
    GITEA_DOMAIN: ENC[AES256_GCM,data:ZdvRrSq/QHiYWbzrSQ==,iv:o8ckvEqOKWPfbfUlGS4ahDu0EHwPK1fna2dBb+Z+KeY=,tag:FQ3jtJMJ4NHhSlfbKxMBtA==,type:str]
    AUTHELIA_DOMAIN: ENC[AES256_GCM,data:V8e+yjztqREhojWAORo=,iv:7i45jQM/Bq3He2SQFlO94nzESW+/R1oyNxVxvAy6Bac=,tag:NqbMyHilCgly8OhALgtVQw==,type:str]
    TRAEFIK_DOMAIN: ENC[AES256_GCM,data:nFvwnfnNp7EP4FQwAeqCGfk=,iv:MsOhXDbUM1bqk1j8y3kn4uA03lETxapUjvP1PmlbQGE=,tag:58VbNScleBfap7TytiGjQw==,type:str]
    LEMMA_DOMAIN: ENC[AES256_GCM,data:otI7+jHaNvd6GHe4M/Ma,iv:RsE2oeKp6DsitShWBVP0CqaNw2maYVQNHZ9MJG8ckZg=,tag:Voqo8eIFbTMRbs2UbOgDzQ==,type:str]
    K9S_DOMAIN: ENC[AES256_GCM,data:GkqbIJ/wJWvQYmF6gQ==,iv:w5ti3CVxp0749WrBcYz9BNy9rZeY2cNFQk68yOlwpFY=,tag:Eu6jmUZWoqCX7OtfVduXwA==,type:str]
    LETSENCRYPT_EMAIL: ENC[AES256_GCM,data:ie5ifNW73UacKu8TbGaCeCgnqpmWrfE=,iv:u9mdyG0q1oGvD03mPWqG2mZ41T+Z2xpzbGlCUfZqukc=,tag:esf8snBS2GVPEANqAao8Zg==,type:str]
    GITEA_ADMIN_EMAIL: ENC[AES256_GCM,data:6u9MX95s8nX+4SCyR0rMxS8=,iv:Jd0x6VIXeOjFXffIZWPw6XZ+XpNLAogJw6BBr8tOGtc=,tag:pJQDo5Zeo37jt5C5zLUSZg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jk99rtxq3ep2xj2w886cchddf7jypqpwkr3dszg5dzq93gn8cy9qyc786m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDZHZWa003RDBDQzRIL29S
            cTRNbjA4TnhmZjlhcFgxYnNIOHB5Njcvc2xZCmkwVEJpWDFaL0VtV1N4YnQ5WU1n
            d25DZHRiRlhCZVJmYStZT284UW9XSEkKLS0tICtiZW4rVHZ2QjYwUERuTkRlYWg5
            TmFSR2Q5V2VKa2FPRXB6cTdGM2k1NmcKwv6mzcdR/rr2NV9cngQg/oGCIcNsu6Q7
            WhF7wkzW4UlfrHObhk10EStsbftf+Nt0aZPTGvoMn9j08uRlcwl8Aw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-22T19:21:54Z"
    mac: ENC[AES256_GCM,data:gzUoPb22M1nQ3a+KK5hh+wZ/NUGiyEBPb2YYGlL0KpFP0qdjtTnMDLl6wxyUURpZu7+ENFDj/uJ7PmzYkSV0nk6CeT8Z0I5u3dBzKjtLIO8G80/ZqUWNzxiUntVHQAys/kh/5ngrPFVwXVPKdj+qTM9aQHAEWa0ZBVEvo2KgqJI=,iv:/Zk4Kfsv3yUJa6prQ0Bug9JiUjgSjsHz1sII+9tWyGk=,tag:Nltr0IMqTQsAK4t5+w0X2Q==,type:str]
    pgp: []
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.9.4
