apiVersion: v1
kind: Secret
metadata:
    name: cluster-vars-prod
    namespace: flux-system
stringData:
    #ENC[AES256_GCM,data:Jw0BBxzhxAnj7GIrMbhN+g==,iv:WTZxMc5hlyzdn7MKswM74vCO/svhg3iln4GT49vQ4vU=,tag:mieWsnrrf/B8H5T1y4XXDg==,type:comment]
    DOMAIN: ENC[AES256_GCM,data:4NQbrw4wyjBn,iv:ip7Om8poyyNqgAY4ywovco/31rnIskW+MupbTI7n/eQ=,tag:YmeZHVnNTqhvcuPe5R+pJQ==,type:str]
    DOMAIN2: ENC[AES256_GCM,data:rVMaOstzy4FboQ==,iv:nMSjDrI7NjxVP7Y+1oY15xW/uhTV3Mpz21BNEiY4ut4=,tag:Z+W7u7Nc93UvqlgFx3Hq1w==,type:str]
    #ENC[AES256_GCM,data:aj4DDjMvYKXhxAQM3aJ1sQ==,iv:RWUt9ZZiQqLeGT6ueghmnfAlpgNGyokhKt+37dD13b4=,tag:3yyLiO/v84h7u8ObuWkepg==,type:comment]
    GITEA_DOMAIN: ENC[AES256_GCM,data:fG/xeegKVeF9fPLUDQ==,iv:gPD7hTcDjSvcOGO6pdouzLxOGB8sd7Y9fY987T6cwFM=,tag:R7mFiZ/OWp2bMGAhi46UDQ==,type:str]
    AUTHELIA_DOMAIN: ENC[AES256_GCM,data:f7rYzUOnN8ocJnsJgnc=,iv:8zP574rUz4xN12rtMSZcrX9ebZ9D6k/oStTh2iyHRj8=,tag:EmKM+tKLubYq0uKVsLTcJw==,type:str]
    TRAEFIK_DOMAIN: ENC[AES256_GCM,data:LqEra36TLr7+/tRdfIT+nwE=,iv:PjumsjT3dkpvf2wS09InzNtwlkLWkKYxOXpid4psjpM=,tag:Dv9w1EIDM9Walju81fcTgw==,type:str]
    LEMMA_DOMAIN: ENC[AES256_GCM,data:IevhGgSjfB8ka6d58ebL,iv:LyNvBf7R/mT9X5VZUnxSnbuCToivZVHioIUtHRmNGWQ=,tag:wsjmqEeAHq3JkawUBTWomQ==,type:str]
    GHOST_DOMAIN: ENC[AES256_GCM,data:EWd2JdPiYCemUi2/SWSk+g==,iv:NJ2crJCvvTjTcjKjuwLOgTHVef2jSJVYLpdd6Uq5mj8=,tag:ztFL/SENhNO8XmBUm2XOBQ==,type:str]
    K8S_DASHBOARD_DOMAIN: ENC[AES256_GCM,data:z/9TK1yT+f88fPmGpA==,iv:ejOHlUeJlpMG2ypF78z5/9LW8pxLpk++rM+M6qD3G3Y=,tag:PqBcaSBhJl4NdMgUgIhT+w==,type:str]
    #ENC[AES256_GCM,data:zWWWi5baW/XQHGa/wXcNpPb7/JY=,iv:pKKIO9my746jUgadCHHQTMGMbLmuykEsEUDKizLh12s=,tag:PRYO0CZu2aeWP1nTEIWuVg==,type:comment]
    LETSENCRYPT_EMAIL: ENC[AES256_GCM,data:nh35+AvkkWpWWXAe+D7/KC4YVgu37RY=,iv:sJNUQ3sP9z9RV7xecVLeJ7mF0fHI7cWmLwGScnHToDg=,tag:uYJPeJgetmRtVTEUoKBfAQ==,type:str]
    GITEA_ADMIN_EMAIL: ENC[AES256_GCM,data:/zj9SFuM7Ls8lU7UPE1VwXw=,iv:YcMWGjjR+mc9gCcMHi89cG9DUoU18+rXGRLN/jviGpw=,tag:k6Es/06lt1ygYgMduBpisw==,type:str]
    GHOST_ADMIN_EMAIL: ENC[AES256_GCM,data:szU+57EML5+sdS8H06zsxsc=,iv:/F620/SZz7UGPRlGicUubhOJ6C6YJKB9fnQDpyEjj48=,tag:43TkMm1bMKDQew9obhdBsA==,type:str]
    #ENC[AES256_GCM,data:Emj6vY/w+DPWU1DEQU8klJFi8HKub+IS0Bm8QFE7dsmu,iv:jkfjZHBNRy37qh6OBjxWmcZ3dL132QiFk/vD4wV8lnk=,tag:tITpTxLrhSt22Er2eola0A==,type:comment]
    LLAMACTL_DOMAIN: ENC[AES256_GCM,data:ASEI60ePW6+5Cfi01oF8Nk3Z,iv:tOmroTrqm1fDRWx8d+8sWjgy1NBSeTZGDdcWGYh6zrE=,tag:yu8hvO3/02tt+difjUCXmA==,type:str]
    LLAMACTL_TAILNET_FQDN: ENC[AES256_GCM,data:xkKPZB1kxFWgbwQIT2gswdDjOV1GWrDkLYhFP2o=,iv:kmJveaOitk7EG8C7tJe+smub+LVEUMaBu5+9cUxXfjI=,tag:UbId9lWh89jQxaHJWlPCaw==,type:str]
    LLAMACTL_INTERNAL_PORT: ENC[AES256_GCM,data:eFjofA==,iv:7ml5uFE79gQ4bkeTFdznROQGijuCzAoo4UBr0FMBILo=,tag:LsxmPn9malDEBoWfzbcVYA==,type:str]
    CHATUI_DOMAIN: ENC[AES256_GCM,data:myEdjYNsmaW93u7T8Ec=,iv:nZsGYc1sQTpvGrKRSmQ7KjjNdoB50YNyoKnABUwK+/o=,tag:8hgsfcJy4qssBvevB7OHlg==,type:str]
    CHATUI_TAILNET_FQDN: ENC[AES256_GCM,data:+02Bgfj0dz1N2BEyddxgvy6jteSR5RILOi/Fgoo=,iv:ennrAgWOgc0BbKhfh+arvATyobMPmkmUZeQjya9ENFc=,tag:1h9TNUyvrbJ7tuxIEgCiXg==,type:str]
    CHATUI_INTERNAL_PORT: ENC[AES256_GCM,data:BC8qQg==,iv:scXuVM8P+4ZLMjm9WgCLEg7Ai3xSegZ36gNXmoo9eFs=,tag:fuj85KMjecylPMaNYPi/MA==,type:str]
    NETDATA_DOMAIN: ENC[AES256_GCM,data:mXJcx5XQSe0Ty3boK//5u90=,iv:23+y8H3gjVau2nBMK6F/OjziaaxCY3p4HrGQ33RA8Ko=,tag:OgjPcRWkRe4AFcL27CVTqA==,type:str]
    NETDATA_TAILNET_FQDN: ENC[AES256_GCM,data:Si7/rLz66Acohm3P6+zL3x0//ZUC4uiT2LT6s9A=,iv:5x5Hjt+53WstLX+cf1HAD6j7eifIluRuh2jUi2DP3sg=,tag:0lpd865HK3RRk4ZHuwDNYQ==,type:str]
    NETDATA_INTERNAL_PORT: ENC[AES256_GCM,data:ZP5IAA==,iv:cVNUSVEVCJsZJKtEHWO4QwMiVk8cTXZIQ77Tbo9mLuw=,tag:ND6TM6ze7EHQWY+/8OTxdA==,type:str]
    MCPO_DOMAIN: ENC[AES256_GCM,data:+a30UdnkIyijy650lfE=,iv:AAcZJRCkYdO/X33ShoT0uu7LTfQto132ocp8GeOPzQk=,tag:DtS2XggQKBn8BdIvNVcujQ==,type:str]
    MCPO_TAILNET_FQDN: ENC[AES256_GCM,data:kYdBG1/GO7lAjeB3fZKIGa8paaiqB4ow4T/Ov4k=,iv:w1Mp9qfLmfMNLiRJEBbvp6WGG4MVGaSdjpGnqsuKVPM=,tag:qyOb7fNzReYrQXdh735QOQ==,type:str]
    MCPO_INTERNAL_PORT: ENC[AES256_GCM,data:Ad2L/Q==,iv:bxIkwCx6PBSaUCR+5qyhv2U0uDsIrS7hirPGk6kY8Gg=,tag:mMcL1Xzd3QRkhAA441fuhQ==,type:str]
    HOMELAB_DOMAIN: ENC[AES256_GCM,data:9L4BXQxCeyM4p0R7zA==,iv:ZfA1Pip89iAVWOCKrHlnHdydoG4bXJiMe6vI4M7Sm4w=,tag:dE5bMhkSLC+rj3zCQAJTZw==,type:str]
    HOMELAB_TAILNET_FQDN: ENC[AES256_GCM,data:dChrUwcC6ME6+OPDZDy85iEIbiTf+ebCcM7kmCs=,iv:fmy8RP6sjuuL7HJJaESOfuJLnrOkY/UQ/WQJ+DX4i0M=,tag:Kq/bD/mTeOhqGmwE7uKDpw==,type:str]
    HOMELAB_INTERNAL_PORT: ENC[AES256_GCM,data:+gKKMA==,iv:mOrokRi4NvXCUP2P75cEn1XVctcMytF+AdFt6i1D8+g=,tag:2mLjy2l+qvj1J1gVeX7HYA==,type:str]
sops:
    age:
        - recipient: age1jk99rtxq3ep2xj2w886cchddf7jypqpwkr3dszg5dzq93gn8cy9qyc786m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuVTExTXpGK0VSVWwxUk5m
            OUd3ZWY2eUExMXE5b3NtUWxIMUJkY3VINERNCnJWU3Q5SnBXTkFXV0V6eTMySnEw
            WUxwVFR6ei92d01PVmpieitDaFUwZVkKLS0tIG14R2VEbXdpaXRyeFU4M2xNcjFF
            cklsSHkwbWRROXVSS2dUU1VYVHJObk0KRNAAjXOH6gUiqQPPwUza+amnVhe586hc
            Mth1h3cja3CFzE5bhOdap87mxLGWuFn+pn6EqVLl+n7PFlWaiiL1WQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-17T21:21:26Z"
    mac: ENC[AES256_GCM,data:3hWz6u3ah9q5GOVu741X36sOAMzEyslX6nTYicpFTiWIG27ToyTJvCDCQHBKnm60KYaDE0hdJHmyfKkbrSof8qNK5z4Qy/6sJxNL9jtify+rm0bEELWRqlLOf3hJ66MMYX7i264I922uz1M7AsNRAhQvoD3O1MV7BDGQSCWq1H4=,iv:z4eUIFEuwvDtAef7/+nZF8KoAZJMXyyUECwS0NWrhOo=,tag:sHu8LFyj+Hp3MkWkLzgMxw==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.11.0
