apiVersion: v1
kind: Secret
metadata:
    name: cluster-vars-prod
    namespace: flux-system
stringData:
    #ENC[AES256_GCM,data:4Cz9Lqci2/QJPo6iDbAEig==,iv:ec8jPlafZyljMTD5Ol6smBE71ltFz2stvNVs/H62eQQ=,tag:pPWNoMWt9JL+edTN1blXxA==,type:comment]
    MAIN_DOMAIN: ENC[AES256_GCM,data:nokZ1n4UQE59,iv:RJ7NEqFh3pHbmla3fpSbAItkhzNVzbkupXIgmV+ehB8=,tag:d8UlCgtRDdxQPOykeXQe5Q==,type:str]
    SECONDARY_DOMAIN: ENC[AES256_GCM,data:pdneeI/kJVz1TDwhRnCWaA==,iv:2DLhllY84N2e0C83uoSwGp4tj8SD+M5ltV/sgzmxby0=,tag:KXLPeolEETAq1enli6FxWQ==,type:str]
    #ENC[AES256_GCM,data:PdzL3Ok5Rh2IKkLCYtqLCA==,iv:iXR3XKHFD/qqk/gNDt0c/QfiE40rIJYYZel/fd7OJWQ=,tag:6h/iX+LFq7riyzMuD8qfTg==,type:comment]
    FORGEJO_DOMAIN: ENC[AES256_GCM,data:+FCXomuDQwvX6tvfMA==,iv:mIrHRG4ljWl3AbnU/zoc5quo2YNAL8khKetn2PDOioo=,tag:u90BS3iYuyHYm5re1+j8uQ==,type:str]
    AUTHELIA_DOMAIN: ENC[AES256_GCM,data:VHuxQe0b9My7hqiqTvc=,iv:NqjdTO2Pfx4ozL8+XmKldxFO8BmrCFO0JwGqDQmV2cE=,tag:lJX54WwCWCzgVgdRxeZ3Gw==,type:str]
    TRAEFIK_DOMAIN: ENC[AES256_GCM,data:NQZFxO6+CHllpM3/i+OZctI=,iv:w/m9qSzLmqATnkgz95aAo1LQ90TIEsoXI6g55sk6h0U=,tag:jfHiyO5gbpE7Mrq4Qj65Pg==,type:str]
    LEMMA_DOMAIN: ENC[AES256_GCM,data:B50tQfVZc0vUaM49UoP3,iv:wnPne2B/xrCottkWRDsks+isLq3HyttSxidzdC3o9ck=,tag:+CdO7RcFFKVOYWfP1OeCsw==,type:str]
    K9S_WEB_DOMAIN: ENC[AES256_GCM,data:R6qt2gB9OYLCMbZkzw==,iv:uO42CRcLJ7FZx+01Fip6ayVRcpBUUfYX+FIIZpZ66To=,tag:dtoeAevxrpoC+3AtAdNJWQ==,type:str]
    LUTE_DOMAIN: ENC[AES256_GCM,data:IxIxQb96f5zLwPHyLww=,iv:OMWpbBRQiLUN0QtnsXopbQlr7NHMisNmtoRukRqsNP0=,tag:r4Y4CWYPp0XdfWaZzLsXIA==,type:str]
    VIKUNJA_DOMAIN: ENC[AES256_GCM,data:1oK3KFSJMqQ8vIwVAMWH,iv:97hgv8a+OwueYYoTGa8v8o2NdQjbQJAImjn8OvI2A9s=,tag:o+uHsBjpunAYrnRJoDD2VA==,type:str]
    #ENC[AES256_GCM,data:a9LEmXY4Qr/vRPeOFmwVM87AWD8=,iv:3ZZyaP9UwJUAh7+zjrujMAdmgP2BmSeiEWPGambemSE=,tag:dFlpKb0Zuc7WAT5vSee2ZA==,type:comment]
    LETSENCRYPT_EMAIL: ENC[AES256_GCM,data:dJK5RwYkp8+ypahGgFYm9pCWoxNsfwk=,iv:eOzlIa89k5qliG6Gbpj2LvYoiU782y2bDIWeYNtdBH0=,tag:DGvPd7kN4Q/iiGN9l+ka1w==,type:str]
    FORGEJO_ADMIN_EMAIL: ENC[AES256_GCM,data:4UlFQ0bTGBwEGqNHrKnRPao=,iv:0LS6MbyNXTFJ+3agOOx1kzgxGfQLRbCJvk1a8z6xHfw=,tag:pW9UD6sAZXO/sJMUX5pr/g==,type:str]
    GHOST_ADMIN_EMAIL: ENC[AES256_GCM,data:nj4SK5jC9fQRIvWlnvROB9Y=,iv:XjcYyDbQwPD7Pm0stq1Qf0HwG6NdVO/FqB3bJULQ0wE=,tag:9PFo5SossGeabjCSvXGNMQ==,type:str]
    #ENC[AES256_GCM,data:Nyzd0Z3YbL73tO3ghMdYnfDDkgtffY4RVvCZOw==,iv:KLaKF31KKoQhTrj1Fxt82YGq00cYYjvhL5NUzeg0y0A=,tag:Fv/CpAbA71umLopd2IEpLw==,type:comment]
    HOMELAB_DOMAIN: ENC[AES256_GCM,data:vdhkRyWvaVRThAb/Pw==,iv:1L9/yBsJWA1oLffWg6c9UupQYti9WqBLNR4hF+0MT2U=,tag:dKFqxH37QU5czqu2KZwWKg==,type:str]
    HOMELAB_TAILNET_FQDN: ENC[AES256_GCM,data:a7LOmwbEp0odPLfxQYY/R1vumHBOhB8MqDVOYgg=,iv:YweK63k6vZ9sBvivwXOHItxz1UYi+hPiji0MP/i606c=,tag:jSZygTUVSkos3sr7JGPXXA==,type:str]
    HOMELAB_INTERNAL_PORT: ENC[AES256_GCM,data:eV74ig==,iv:PLSDNbm/eZ9tc8HurR+k+O/9KIFuA3Ehjnim1shD7po=,tag:DieuAsCSeTfM9NO0B5Xq4Q==,type:str]
    HOMELAB_ANKI_PORT: ENC[AES256_GCM,data:uYOirw==,iv:q58fWVvf4HCCNKguBny6YunRJqPTGcdGDe+mkV7W+qI=,tag:FYCJPCdU4eL3mn30ja2PIA==,type:str]
    #ENC[AES256_GCM,data:NCzFJCvGRwGy8mmNLwGYPfxrDtVXacBi,iv:OR2mvU0stZw0fEz1kNuiNn2ddxuOskNPzYN6tUnpt7s=,tag:8YCaHTt8LjU2LH6kzOkM+w==,type:comment]
    BACKUP_S3_ENDPOINT: ENC[AES256_GCM,data:RQzmU3DxG9tzVNp+/AvVBTRJaAx6/IMfgwtL,iv:2FR9H8b1SJykKsHid3Hm9y6aCqNyZoTu60nwWW8XXRI=,tag:bIRSj8fMkO23r5GEfzQnWg==,type:str]
    BACKUP_S3_BUCKET: ENC[AES256_GCM,data:WOSoweLGpMmu1ggde4Q=,iv:wFGT/eB97IEJcEEmk7Dl6VoPhf+b+kFVQIFo3Cw1Bzw=,tag:ux7cTlwB6tkppGHt+rx2lw==,type:str]
    #ENC[AES256_GCM,data:LnO8++jK+Oc2Txrw4KLOiy1Vw+51iA==,iv:EHRDUjE0Dyu22cJGhPDrg48g/ak3dB1wH7xG1jhOHOQ=,tag:YGHDOReYVvc7xBmQnMLtcA==,type:comment]
    CROWDSEC_WHITELIST_IP: ENC[AES256_GCM,data:3Hk1KXgzr+1hRNy5MKg=,iv:fGjCyyWuqDD6i94gds3aGxU4Bw8EAYDJDZQV2KUx2QM=,tag:XN2qzrI172conwYh80hMWQ==,type:str]
sops:
    age:
        - recipient: age1jk99rtxq3ep2xj2w886cchddf7jypqpwkr3dszg5dzq93gn8cy9qyc786m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArNXd4aEpjSU9sbFJPcXA2
            U1I0dWo4Y04rSlF0ZElhbUxQREs3RDdubVRVCjBBOFk5ZmlraFpGbEx5NHVuRWFT
            dmQ2LzMvenlldkRXTDVyVHZDbXRMZ0kKLS0tIFlmZFNISlplemI5MVBNM1BCQ2Fi
            OWdzV2VhQ1FRa285MmJqakgrVmhudjQK168MBZGBIkh5F8imu7+UxFz+7l+F6wEj
            uUi/wWfWhGqbJB/FdRo8Wi2LCTwLn6dfFTRFar3phxtw+Ocf+VlOyg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-20T22:57:17Z"
    mac: ENC[AES256_GCM,data:l+zB7udzQ+ngs3bUzLtRKgRtWR+wM5kMwA5j95/sDIqoVz7XG7Bj6QbbMxBwgxF2Xko7vAREsdHUgTKWWr36r7+6DswN1nDi7ufoFWfDf9qJ/1zQ1Knd2prBHfAaf69psjNkFbH1AHqmsXyzAdgJB7x7Wzz+HNWTQSuAB6mSraM=,iv:zME/+I2F8yGA9V0p31y7wOgJ21bmQuWbX25538CWnTY=,tag:JHHNs0YJYYfjL3ThOaABfQ==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.12.1
