apiVersion: v1
kind: Secret
metadata:
    name: cluster-vars-prod
    namespace: flux-system
stringData:
    #ENC[AES256_GCM,data:DJqvr7kWF0hNc8s4oa0gmA==,iv:vWFOMIQGndwiuMGvvF387GGKxR8lkMVlUDpbGJubBoQ=,tag:/t/C4rzVBqBSV474H/FSVg==,type:comment]
    DOMAIN: ENC[AES256_GCM,data:RBZ8BTPEiVyp,iv:lYB0rM7K7Wiluh/ussyT/iDSOP9nCJFj7vs473KoueQ=,tag:NQfNXmqeflxKik1jqh9bMw==,type:str]
    DOMAIN2: ENC[AES256_GCM,data:pRZmsNCOgFk6jg==,iv:tOGL/C0sr1+ohnQMWCpgTkKc4Zwt/hJO5mekwJgxZEs=,tag:eigMKtMMQSth+5nR701Haw==,type:str]
    #ENC[AES256_GCM,data:0S8gWvhdH3prBLf5edUpwQ==,iv:aGF8qFplvk/TEFs3xqruePsUNhIGnxcza0rAzM1LAiI=,tag:6rUBE//rWG3JzO0gdHv9sA==,type:comment]
    GITEA_DOMAIN: ENC[AES256_GCM,data:Z7Z4J00MfnhAybaiJA==,iv:xcqfC5F6FVuQt4bF8WBssTJEiDHy4aLQ+N4MizFSTQg=,tag:KwwR2bccrY6LyfBerPeI4w==,type:str]
    AUTHELIA_DOMAIN: ENC[AES256_GCM,data:MrRxRei+dSdP6REXykw=,iv:1URMokdO31sJCayANcaWMZLXkt90gdVrd85+NDrHsFI=,tag:PV25elx3Mdu0vv+a+3qGYQ==,type:str]
    TRAEFIK_DOMAIN: ENC[AES256_GCM,data:GQDpDaHkxb02g5eMTSJ+yMo=,iv:iZUP9OovZjs+luDQv9kN2bM5PYYrfCKFXyFMh+TOr3g=,tag:W7HUkACCQUuSu0esilfGbw==,type:str]
    LEMMA_DOMAIN: ENC[AES256_GCM,data:8zWJoNyPkb4TowRKxGW6,iv:Qa+jZfDLT4IBrleTTu38ErXfhKSleHmo+mn3QispghQ=,tag:/lXbNqj3/qfmLevT0/GgDw==,type:str]
    GHOST_DOMAIN: ENC[AES256_GCM,data:kwg6u1Fc7EGyIPNKOWKs/A==,iv:4aw+ZjbmFp3Z5iFzuf54KXSCaDRX6zqiULNio8NMllo=,tag:QOcCZOce0U0BXjo6AVivRg==,type:str]
    K8S_DASHBOARD_DOMAIN: ENC[AES256_GCM,data:EAB0qB2EJaYxdCK31w==,iv:+3Ubu9tLvu6kJzaa+DR/4rLPaeaUNWqyyP4eNyTGLxk=,tag:KlNalOfJ88C/kFQivGRvpA==,type:str]
    #ENC[AES256_GCM,data:W7NOhcmHPCh3fV9PuRWsFWnMhFo=,iv:mMxFfYJW/yPIyYHIy5WjBBanvtZ/hUmT2dEhQ52nTDc=,tag:ycS3B+YFy4c0ITrxyEGc7Q==,type:comment]
    LETSENCRYPT_EMAIL: ENC[AES256_GCM,data:0qs6u7+CDOCEzdozxPFoQ6qDiTbEr0A=,iv:s/aYQKs+uf53Y4Z5qdARUVA5sneyn5hqXkiWnpYLRq8=,tag:J+98O2eoCoz1BlDl46K8ZA==,type:str]
    GITEA_ADMIN_EMAIL: ENC[AES256_GCM,data:qQT/5vg68BFpjC8Wo8sYtdA=,iv:OELfdS8KtF2oZq8HyH1rjjIzo5++4Jba108K3VzG6wM=,tag:rYRwXBnTrRDSU5/QQJctng==,type:str]
    GHOST_ADMIN_EMAIL: ENC[AES256_GCM,data:CNu9kJL8kUHxd+WWB3Dq//8=,iv:1la+LAOQkTYEXvzZ4wMgdpleop/pwQqBAfIeJBwIHfY=,tag:XsdXXs6TiekmiLKFD9QDeA==,type:str]
    #ENC[AES256_GCM,data:fpB0688GxsJhbUGJo/oFvhwxmZRv,iv:qMWADjc1ju/Yj4HQC70tVpgpGNsy3tKDsyNmLqke/D0=,tag:UTALoTr0kWVdcEFVfXdOmg==,type:comment]
    VELERO_BUCKET: ENC[AES256_GCM,data:V0uALjZhpFopnBeq,iv:Veh0e45blkw52ldQFgG9UT2Xqg8evdYnViOBq7ZKtuU=,tag:blS0GCSqpMl4AfSMykMQxg==,type:str]
    VELERO_REGION: ENC[AES256_GCM,data:LnEKRGMD,iv:rxpH/alj4w8ev0rNgMOneGCSzt2euv2LBat+hzxNvtE=,tag:xsCGoDf2pWEfb7iXASQbHQ==,type:str]
    #ENC[AES256_GCM,data:YV2PnLebxvlMBj2+YAyyTAk85fRMBq4XDD+LsYut7ii1,iv:3jZqAcPtMDyuJHJHw4W+U5LjhJ/sF1yh1wzgC11A3W8=,tag:bCW4EE7Jw5pSZXpG3kfJow==,type:comment]
    LLAMACTL_DOMAIN: ENC[AES256_GCM,data:nvZRVmNlzZeu27oK7v66cdoe,iv:Q762pBjkcaKcq8NM4fogwsQHbGogWf+GcEIYFcnkVNg=,tag:bUIgdRWRhlKicKdVNdSEMA==,type:str]
    LLAMACTL_TAILNET_FQDN: ENC[AES256_GCM,data:ATitqz1CpVztUauVro+CoSQNU86xNVcoiUBI6j8=,iv:TzGbSRjU6EEjnDAAOj4fXwAD3OoQHfNTB5zahmLCYac=,tag:JOrdrcpv1UeyNg39qup60w==,type:str]
    LLAMACTL_INTERNAL_PORT: ENC[AES256_GCM,data:+VhlPg==,iv:2Rel9/FYYrnrwtYFQNLfJXrLrXhgJ8GptrK2O/9Mww0=,tag:ff4titimyDvXait93rBIAQ==,type:str]
    CHATUI_DOMAIN: ENC[AES256_GCM,data:03vQ/iJjN5k3LQbkRds=,iv:+MCUcwYhrLV4wO1hzzYxRpi+bJdGgaR+XnCxJWVAQxs=,tag:ujjonzknl5iQZir5/JAMfg==,type:str]
    CHATUI_TAILNET_FQDN: ENC[AES256_GCM,data:KvqtYGZxngFMZj8+bJvLE+WSRUjZ438g/ufHRRI=,iv:+2yY9LDPPZfL1rvFmXNFVmwnbAF367KgsBRDzbzSu2Y=,tag:JULNKI/uEfj4hD+fTB/QRg==,type:str]
    CHATUI_INTERNAL_PORT: ENC[AES256_GCM,data:F8ckQQ==,iv:L7B4ot5Nb/5xXc51WWAXGQjp8IVhZ7RkU02ePv9ItFI=,tag:7vMxkTPwHO5JyBq4TzFEjg==,type:str]
    NETDATA_DOMAIN: ENC[AES256_GCM,data:qnB0EBSN2XcErMgKaEuNb0I=,iv:AZOwFun+u8H76MwOGzyffikJBFMOljY6SjE7IUto6GA=,tag:yfZaL2h40GlGq9xoMVvBJQ==,type:str]
    NETDATA_TAILNET_FQDN: ENC[AES256_GCM,data:Urw5ayazwW25BYy/PoQ/aq1q1wBT81dBT1iFsaI=,iv:/ZbHF7RUVskXnPn9BhY+uUtcuIXD9NzMzR7K34k0PlE=,tag:fJpkMMN/qdRdbsk1ovFCTw==,type:str]
    NETDATA_INTERNAL_PORT: ENC[AES256_GCM,data:dUAgojk=,iv:L3Y+pJSjQFMm2e9JA+nOfdBz4kWr2UQF3PKb+Yy19LU=,tag:UUBX6Jn/IQClw7R0ye/kcw==,type:str]
    MCPO_DOMAIN: ENC[AES256_GCM,data:NciBaOCjmH09OLiM9Mw=,iv:6RuMLH3aLHyJ8bcy2FNBQB2S77/BYcZPmC+23k+xCuI=,tag:e9Atov2WtMawIN0H2NoWVQ==,type:str]
    MCPO_TAILNET_FQDN: ENC[AES256_GCM,data:cNrpL55sVlCZ+hqlwKo/Rm4uC+KiAVCn2a5SZtY=,iv:A1j7K+H9HZjgPeLo64M4csAfYHDuK4SlChjVBd2JH3M=,tag:ExI1RN9u6wsRqVcUX+iOBA==,type:str]
    MCPO_INTERNAL_PORT: ENC[AES256_GCM,data:kLwABQ8=,iv:hvlzA4aCbVAbxUkmDevQEyPH7zpLgmOlIkNUZ9D7EMI=,tag:csJj/A8an0KtfQ8lbPt5dQ==,type:str]
sops:
    age:
        - recipient: age1jk99rtxq3ep2xj2w886cchddf7jypqpwkr3dszg5dzq93gn8cy9qyc786m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMR05TN2EvMkE1TVJlMElz
            T1paK1BMaHBCZ2FVZy9SUG56SEpreGRGSUVNCmMzVk10ME0rTkFlNmtLQXhXUGVH
            Y05wRU5uVEZmc1E0ME1YZmhOWGpzOEEKLS0tIG1JNS9JeG44NFlQcXEwZDZQV0tU
            cXhSelVXb25iYXBTUUFsZFBGZmlsNGMKT80LuwIxALeoOqtHAl+kv9TZ4kAs5eMm
            NYTECGzWkx84OvAcyyT+zC0jKNnGet7CRWWiI83Px3dhY8BOMX+xSA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-30T13:33:02Z"
    mac: ENC[AES256_GCM,data:QoBQr1BKr3LU4wgZkEof/Og+Bemq/C1Q5T+wTSDwBVluH7xBdU7jsNF22MNALJstBmdahSMKHY5foc3E94ErYII2VW/ZQzXpBh0LfYLCIXi9zEcp0ZJKtF+ToWiech/ri+vDGjWraY8z2+7rBfp2EBzDb+nDh2OksVYmEHI3luw=,iv:IWuqmUjrBN0ehWY6ZhMAt9XFLhYiGSqeNHxrrlEfhuc=,tag:meSqkvsdIMFThQOhR9GaUw==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.10.2
