apiVersion: v1
kind: Secret
metadata:
    name: cluster-vars-prod
    namespace: flux-system
stringData:
    DOMAIN: ENC[AES256_GCM,data:hspqE3KTyQ2S,iv:h2cOsvCQSLFYStMBQZofgcT9QY+g7zYxzQdmx0Td4TU=,tag:jIMkm2M8CBDXGw+QzIrkHA==,type:str]
    FORGEJO_DOMAIN: ENC[AES256_GCM,data:6Ot9loYFMonEHDjAqQ==,iv:EoCdUIgiz5apUZFGkLos/BagK/f2ovqpkYh0SY4+gqw=,tag:y3DLvQaI1i8DYpHRc6Z8LA==,type:str]
    AUTHELIA_DOMAIN: ENC[AES256_GCM,data:wjOQOkHWhtX8E1uuj3A=,iv:25Pq1aynEoMyJDvGHND9CtMk5X5SlqgZwdyr0bF2DbY=,tag:iPv5Iq+6sXJd8NNCXpin7Q==,type:str]
    TRAEFIK_DOMAIN: ENC[AES256_GCM,data:m9gJab5smUhtSjN0WItcN50=,iv:w3mPkUqXuhGsEwqhmlqjHPBPkn/m5J8MMJdo7LCgmPk=,tag:4hquarjVPd8FHbhlfexQgw==,type:str]
    LEMMA_DOMAIN: ENC[AES256_GCM,data:8RqUkFjDiJvWZfdIRw9o,iv:kKzX2oNKokbRXKg3LtniPggmn0bcxXVgUae3IhCUgUY=,tag:qsq+qc1CtC7YnLBdxoGuRA==,type:str]
    K9S_DOMAIN: ENC[AES256_GCM,data:tkT2keAX5GKMZUQwgQ==,iv:JtYFVAcLfW4/qKMq33sTY1LrG1OKXf7AiSHlEG6ubW8=,tag:PUwXeOihGU+2fB3JuCGkPA==,type:str]
    LETSENCRYPT_EMAIL: ENC[AES256_GCM,data:Wg3O4ft3Yft25hGPWwFF5QT1hQuQOiw=,iv:dQ7Z5yM7XiMTR22WulH55zhRiuvsbPnDZhwijb/d80w=,tag:a4SsQWStYDfWmlG3u0rX1Q==,type:str]
    FORGEJO_ADMIN_EMAIL: ENC[AES256_GCM,data:C/g6o/CMgG+VwF4HQq3/rWM=,iv:Pn78C96OCSS5DiDqHi0lKqqe+aCqp1GUq+d7GpNiXYk=,tag:rtH9XmaUaB89tTB/4nK1Dg==,type:str]
    VELERO_BUCKET: ENC[AES256_GCM,data:S28dwG9RUFNO9zR7kmrsyoyMHQ==,iv:D7ePZOeHCeGJ5tX3WN0krYbOaS2wwuljsLjCdkZ4wNM=,tag:dxVVZbhhg8fnyNq2hdSM/g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jk99rtxq3ep2xj2w886cchddf7jypqpwkr3dszg5dzq93gn8cy9qyc786m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBabi9EZlNCWGxkd21tYldH
            RzNnc0xpcndRSnNXcnkyMUNZM2RzYjl1VkNrCnRJcXBKS1RIRGIwZ2loa1daOU40
            dmkrcEtaWUtpVGFoSGZtNXdrQi9WM2sKLS0tIGoxSmdESWdqNit5QnRUdEREOUtj
            eDBTQ0lkNEhQL212bUx5eC9FOHB5aTgK6wST/JmNOEDz7B+Mu6mYJwVu8ikn+es9
            ppB3GYBik4TTKqoKljoO0o3RjhkUPumY4eVvpD6DhiaCZdKn5M15Lg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-29T12:08:59Z"
    mac: ENC[AES256_GCM,data:A8aWMegv5tMo/VXdV9X6Y9NjCvpHdOLe8YCbdHCemg6oEDedkl0Ydj+oXGfAcjftsglVJpHf9w/nfSQwyUaQSFcxDmiQGIbIrHLOPoRixz04jkpzmY+PiExaZQg/fgorpuAl187VtA9zSuBiUDOEM3GCjJqa70uATZiCSHcWYV4=,iv:mk3HkjT6970bop90R13c0C/0r+W5dEWABEFugp8xlWo=,tag:04KQUXNGOEYhMcg5TcKSTg==,type:str]
    pgp: []
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.9.1
