apiVersion: v1
kind: Secret
metadata:
    name: cluster-vars-prod
    namespace: flux-system
stringData:
    #ENC[AES256_GCM,data:a4k9ytmFx3E6c0X96gTOsA==,iv:gZ7IJpiNg5HWR9u443nxA8QfZ+4f9OBLCp9oKnWkY9U=,tag:y6q6WuLqqkHW+wALYRKvRA==,type:comment]
    DOMAIN: ENC[AES256_GCM,data:feCqpoevCJJi,iv:YLaXqcMQwhAorw/q2RnFrxOtmOnsVluSkgQmpkr+y8A=,tag:SFn1HI0fEX978NDflOUJCQ==,type:str]
    DOMAIN2: ENC[AES256_GCM,data:crZu3qv3/uTzCg==,iv:9bbWayyoPTJKz3uGRUAQACYdUFhIGrGwDvb1No6770g=,tag:f1c/pW9se26Sgs3oDajwAg==,type:str]
    #ENC[AES256_GCM,data:QAELkaOZY2Bt5H0Rrb1FXg==,iv:ADGFMjGqhrgW+UYns+G9ceB/LHeveaihQPhNnkuaSCM=,tag:hV/d79qpfNWLfV7BbUbkfA==,type:comment]
    GITEA_DOMAIN: ENC[AES256_GCM,data:HCnCK2JaiN+kcKBpCw==,iv:9QKrcXna06ibmBGTVkg09MjgkiezcxmTcmbvuJ3NdlY=,tag:rTZS0A4Gv0IioDzLqC+hvA==,type:str]
    AUTHELIA_DOMAIN: ENC[AES256_GCM,data:a8SJrw/qTeGp5+11Ugg=,iv:C39fGuYbt3UiJrJIRuApNvGOGvlnvT8TI5W+Um5l7lY=,tag:ETpZ7571WY/ajciRACgRkg==,type:str]
    TRAEFIK_DOMAIN: ENC[AES256_GCM,data:eoTuS7PwzvqdK2BM9EjNR/c=,iv:pb6U24JQLVws42N6A0zS+8ChqzEQHUqMaENdnMTyYzo=,tag:uOGpboCyMaRNcR7ocb/B4Q==,type:str]
    LEMMA_DOMAIN: ENC[AES256_GCM,data:HPckcX2GhyImjsCjuM5P,iv:ribxs9prdQPjrbN+FEBqAO9mk0RZHV50e6oumml3sTs=,tag:aNFcgqWx8BZZFo29admXmA==,type:str]
    GHOST_DOMAIN: ENC[AES256_GCM,data:73gxN3s2MF4ccptLSS9aCg==,iv:+xHZkk8b9vgKoDb8c91wGIF1K5nxCnLaka5zdTIzhZo=,tag:XLRKUlXIJXdX1PS8dIY6xQ==,type:str]
    K8S_DASHBOARD_DOMAIN: ENC[AES256_GCM,data:Lus2ePB270IDzU1UiQ==,iv:hUnwLPB23XCM12e/WOWZgDOZLfTJSYR8jmSk7YHredo=,tag:pkMTgquvyTLOwV2BL+qNIQ==,type:str]
    #ENC[AES256_GCM,data:G3DQM0n+TTI8NMn+Zyd7vHAaZG0=,iv:/+cNqR+qHP328olwvjckGNLtOPqDXUF+WoGS6t0kv1A=,tag:KJww1lwvVHGYPyN18YrCAg==,type:comment]
    LETSENCRYPT_EMAIL: ENC[AES256_GCM,data:pHuATMlIA4qTQHsLnqjElS7iulLjDiA=,iv:3F1y47EipVJ/4kFy1Yu9nTp+r6Qi4unFSX6BNot1zs8=,tag:liDfdGI/29nfSHxd9jiEsA==,type:str]
    GITEA_ADMIN_EMAIL: ENC[AES256_GCM,data:ffs8FiQpLhTjA8uHp0FU6SU=,iv:gBhBcUkbivxkYt04lRSuBrtI6aE0KbR6dVpsAPXFTxE=,tag:fZ/MN/YmsyephmHKW9+xbQ==,type:str]
    GHOST_ADMIN_EMAIL: ENC[AES256_GCM,data:RMFYa+r4zn1rYarV1rTLmZo=,iv:DJunw+j+JAWLxWIrKeLD31hvG/f97ZZ9uM9St0CDPSE=,tag:3SM7YmSuKkt4gNGVAB8Dyg==,type:str]
    #ENC[AES256_GCM,data:rr9sIYYmZgdSZfaTJQ6R4Gq7liSsxia5YddIlQTWHeGJ,iv:eHkgabDe2IY9yqww6a4K8bKSHYE7l8grzc3D7RohtNU=,tag:JBmnp1M57c/e7l7sVraUjA==,type:comment]
    LLAMACTL_DOMAIN: ENC[AES256_GCM,data:2W43cQt4wu31dL7+xeYp0sKM,iv:O0HL/ixTh5sIuctvgtQMcigPSM2saCXvkprZSVJpL+I=,tag:aYY+YMmGkLhVwCvWXWInMA==,type:str]
    LLAMACTL_TAILNET_FQDN: ENC[AES256_GCM,data:PEEY8q5D+UjdWE/7kAV+GE1gW9OwL8Bc5iGoFgI=,iv:e4MGRN9pPGzJCvku2qhWxtmMZDb7Mpwzf3oBXlLdgIc=,tag:wR7khC+QApQthovEegfHWQ==,type:str]
    LLAMACTL_INTERNAL_PORT: ENC[AES256_GCM,data:AZMugg==,iv:1YUGM1VaDB3yGkIDEMIx1wkuml4xI2DubH/qAKomHmY=,tag:RiTrDc7QnRupGkjUIQe7+A==,type:str]
    CHATUI_DOMAIN: ENC[AES256_GCM,data:/xF69d3out6gzBe2Kok=,iv:wbf3v5M5PXILO5+2++skjSI/OjygRlDgigY/JTXlttQ=,tag:dwZPIJ7+H9MYt+RLLGes0w==,type:str]
    CHATUI_TAILNET_FQDN: ENC[AES256_GCM,data:hu9KzgHW6g0UpWSCXiOCviigLHlvuVEXKqLxGOQ=,iv:DEe7P45KX4jqyXIZ28HaKh8NWcOaQ9kzQGiR9ytsThE=,tag:tG3V0dKbIt8ENV8AlxDMvg==,type:str]
    CHATUI_INTERNAL_PORT: ENC[AES256_GCM,data:GN1k8g==,iv:sf/Oy+VQ27hVBh4MugNfqOnmz0zA6dXhLNGolr++njk=,tag:ZnBUw5IscCDRDwhxElJ4LA==,type:str]
    NETDATA_DOMAIN: ENC[AES256_GCM,data:7Jfq9uVTLP1LYloJh1xJRuw=,iv:DjJhML4HJHp4tRHN3LFcdvl+4W6LPbn9YDmjIRndAM0=,tag:s8B5jb+wt9QyXgBrW0diSQ==,type:str]
    NETDATA_TAILNET_FQDN: ENC[AES256_GCM,data:XU7lvF5prJf4VEIhGQYh5oxc8GPzzDBSoc02RHM=,iv:2lUYtQn9UHtbNDnWxiWxDXkovpwdIzbOHe30C4uDqUw=,tag:OL0BeJ+WXZVaVSRhUbjccA==,type:str]
    NETDATA_INTERNAL_PORT: ENC[AES256_GCM,data:hOij+JU=,iv:HIl2YbgxEYG6DZlIJ6RltlbinjqLQ4HpoSV5qIGogqk=,tag:UKanGAUOlcINoqLu90Ul7g==,type:str]
sops:
    age:
        - recipient: age1jk99rtxq3ep2xj2w886cchddf7jypqpwkr3dszg5dzq93gn8cy9qyc786m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMWUJ4TStIWWg3S1o0dHB2
            ZlBNd1NjdUduUUNCMStwK1NHVkNCajdtOFNvCllpekE2cTZRT1U0a2JyeityVExR
            MEJQa0luQlVCVU55ZEVZSU9FNFp5eGMKLS0tIGV1SWQxSUwxbmltakZUTXQxUEpk
            bURvR0VvMkZrc09kWFF4L3BmTlk3WTAKBuPs0wVtdDbygS+r5sqOjjCBsytwq/sf
            tyEaWypgBBr+HCI+R24X769zfOHC8tXyU/EqWSznm+CqlLtgYeOiyQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-26T18:31:25Z"
    mac: ENC[AES256_GCM,data:IM0762Q52R7NGXYt5uor/KXv1+QO6zVBSlyfpSznLwSnm25OTvwA+uKPc/PO5Joj/bNviXXkXmAIW8Sot3+6AnZK57NNg4vBcH7wdEcp6jHV3jRj6baRETgqqjF5JWyNFXk5sCDorqNGqZUJttELUjuziLjy+9pvjpqyx9DHSts=,iv:81RddYX3XD2ffgvR6YauftyuXXYAYQcfRJl4a4Z/Avc=,tag:B2oAtS0QKS4S/vW6nhR80w==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.10.2
