apiVersion: v1
kind: Secret
metadata:
    name: cluster-vars-prod
    namespace: flux-system
stringData:
    #ENC[AES256_GCM,data:EBWgghUsSt2uh5nsmMXenA==,iv:Vdkn/EQ6FEQKUvkLyrFri+bXNrzPT3JKl997qIvj7VQ=,tag:r1VkHh7rQi9ZzM473cS7ZA==,type:comment]
    MAIN_DOMAIN: ENC[AES256_GCM,data:6lCB2kpaRe+l,iv:UkvCd98h/7kUu+qq9kxEOxeVmZiaMW1AmT/uwtCh1L4=,tag:qbIcXauzMWZlPrHk6S2pqA==,type:str]
    SECONDARY_DOMAIN: ENC[AES256_GCM,data:po8Ey8M0hUzCcRS17R1h6w==,iv:yK9iTvtzz22JNzW0HkkBqjS0vWxsmc7QBY3Y0H40LPo=,tag:75XW7llHPx4oTY2VydPLvw==,type:str]
    #ENC[AES256_GCM,data:ZmwdfQtzs3JWhuxXxXoUgA==,iv:0imjGzU74j/8GT9WdwvA3cSuCYPC640SjBaLibnyri8=,tag:3CTooncjo6lVzMGcMSeYRg==,type:comment]
    FORGEJO_DOMAIN: ENC[AES256_GCM,data:hpxIvKFv2jne9w4Miw==,iv:YvgZNer8Bb4/cJdSTSE8WQn5joocfoxze5TxCmQotDM=,tag:1AJ+J1gsKkpeFnz0DARKYA==,type:str]
    AUTHELIA_DOMAIN: ENC[AES256_GCM,data:zM3V0O1gv8iG+NzenPE=,iv:YRxm2ds3aQ+O69Vf5yPKANIPplYVerQUSTxtDmsiIGU=,tag:D/wpeTh85gJQTlNvB9alxA==,type:str]
    TRAEFIK_DOMAIN: ENC[AES256_GCM,data:P977URHRzubfU5WzDg/rGFU=,iv:khH/q2Ge0Lon2gDnZNty54gRkxtVwB3VzsKUYkZjyRI=,tag:+ibXmojIvxmaYNxIwpfLpw==,type:str]
    LEMMA_DOMAIN: ENC[AES256_GCM,data:4QQHbQcAFUr2O45GFyuu,iv:8RYn+KcgdayXOSkFbD5KKfz+2zGf+OAoLYfcnJREpyM=,tag:5BTLmXTDzZ5c/QS2Lli35w==,type:str]
    K9S_WEB_DOMAIN: ENC[AES256_GCM,data:zaTcoXMZb2HS5q2sxw==,iv:UkXjdHnLEt/C4884aBaAvOWPb4fjPaCZkRk/0e1lx3c=,tag:Mw66RqpAL0Q1qSGe7TykKg==,type:str]
    LUTE_DOMAIN: ENC[AES256_GCM,data:LljmLTgL+j6uOY7mr7s=,iv:FkvktR1/wPhr5lx9bZByiNhsFz+P2f3C4RHnIno0CxI=,tag:d/g+E3K82EZ+1CwKbBgXdg==,type:str]
    VIKUNJA_DOMAIN: ENC[AES256_GCM,data:ZjR5WEVKyOc3uV7oYTcP,iv:ixi6La7GerTpCxh9i8E3dtqiVR4XBzjY9jP3akosVAQ=,tag:Fua9qRcgSSWwquyJUXPOLg==,type:str]
    #ENC[AES256_GCM,data:rneGOJkl8hUcQDnL6O3qSjlpxhs=,iv:4TUgSx4kcoyPkqNKVJJE7Fpx8lZ0OPY5CBWJ1WgpwUg=,tag:6rd+OjPNGBMvhKDnT4/VQw==,type:comment]
    LETSENCRYPT_EMAIL: ENC[AES256_GCM,data:gAC95xwHPbcZJORkVuK4Zo+clDtKHlM=,iv:hZ0KpPL05YhTWRSRzBTgzbsTXk+KoYiaJbMClBaylKM=,tag:L9zTiV2UMSkcB/inwYyxYg==,type:str]
    FORGEJO_ADMIN_EMAIL: ENC[AES256_GCM,data:+8dqY+qxYIsRucX1DqpN+Co=,iv:BPFjuOs3JZ1jzFClYk6J8C5xu7n3jPWfdjWrHeFgi+s=,tag:wvX+XmsLNmyz7W1LHsWlbA==,type:str]
    GHOST_ADMIN_EMAIL: ENC[AES256_GCM,data:8lkk7LBl4txH8IMCtcWtpFU=,iv:azHgpU5jIIaalEp43dz0g9jcA1Z2VCrMOziiuc9j/iw=,tag:Jb6TyRZ+42cqj56GcH8OJg==,type:str]
    #ENC[AES256_GCM,data:NcM//BT57kwaIi9SX6f9roGlnKHsg1ksPLrZ9w==,iv:J+c/CzZXuxdiFrVsKd+JqYG/8kMxgUbgVIIhkvZ+lFI=,tag:5twoN+k/WbEA46nvE82h+g==,type:comment]
    HOMELAB_DOMAIN: ENC[AES256_GCM,data:YgcfkMnFMlVHPLlxRw==,iv:qvzveo3HNfRXKRYKWp840gfyf5gE9Y8c6zuGhjotH8M=,tag:IkLRYHeg2v2MSzlLMbrGmA==,type:str]
    HOMELAB_TAILNET_FQDN: ENC[AES256_GCM,data:pfXvy73HJ1lR/u4/yiJuypbWWh5RrRzLzaI7Cg8=,iv:J7XUYYf67LzRuoRBu2u8a5EXVawpDgy7V3rmwjUAfms=,tag:F7uzJc5vVyn4pjWDaJw4tg==,type:str]
    HOMELAB_INTERNAL_PORT: ENC[AES256_GCM,data:JcHz+g==,iv:mXZnzIlBg3US+mJTbfA3FF8wt1IM+W/Fy9x8Q4VUH8o=,tag:t0o41p4Vnn3LIMGWmOSgsg==,type:str]
    HOMELAB_ANKI_PORT: ENC[AES256_GCM,data:JrB+YA==,iv:hN+dDVjyGdp9BmK6sBtpRydsdH5H2RXdZ4FI39IG/GQ=,tag:qwzXeum0h5ydiTLFf46mLQ==,type:str]
    LLAMACTL_DOMAIN: ENC[AES256_GCM,data:QTEMIlgwUreWYxttyMNZdMs=,iv:imLN59xLNHyIycpBWStqEVV0PVTeWbDtF0U62fo1/B0=,tag:z9OYfX9dUnCV2CgNvfKQUw==,type:str]
    #ENC[AES256_GCM,data:Hb/N9moOONLCay/ZQdfFuCE5GUrnlqbd,iv:T1x+N+Vzc9b98AzCeiJypo0XEmj2QFWf2YhISjBkmww=,tag:Xse16hLpD5x89gXg0H1x/g==,type:comment]
    BACKUP_S3_ENDPOINT: ENC[AES256_GCM,data:8kh0nhyomdGupvmDUTvIUIsexYddWHkxK6eo,iv:LBnPhziA3Vl8yJbihk0dY0vvnVnyOqiimhDh9sdy+ac=,tag:1ZHqwX1KhkYKibxzzhxY7g==,type:str]
    BACKUP_S3_BUCKET: ENC[AES256_GCM,data:ZaX+kx5ImqrGQt+xq8U=,iv:6u/wMDFIhCdeeNkPJSa3jitDvRjEx3AO4P8vdQ9wdHc=,tag:Yp/UBD04Y6mE1IPV2kjzuQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByWXFaaW04UFlSUG1XWkJl
            SExNYnYyYmtYOFVkOFhkeUxGSlIwaUV5SkVzCmtCaWlYVHJxWnhQVzNNZnc0Z1d0
            ODMvOGtnY2hhME9Sa3E3TDRFNWU0dDQKLS0tIEJHZ3VpbDhEeGM0VzBQdkxLc1ZN
            VWtrQXI0Wm1wOElodVR5UGVhNWtjUEEKsBFckcdNplrpPAhAXACDKfh93fgkWrt/
            UTnVOY7/ybbUaMiBVVx4hngjbpw0sfHK0diILeTsS0jslhn+1aZjpw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jk99rtxq3ep2xj2w886cchddf7jypqpwkr3dszg5dzq93gn8cy9qyc786m
    lastmodified: "2026-10-06T19:09:06Z"
    mac: ENC[AES256_GCM,data:ijgtxNXaoA4clo0Zi/msxoAaIUNSgRV2JH4gfClVDG+/emmYUVQmmAP9h2A2ucbRN4fGe5/xd5quElB7JB7vo48JZf576re9ctsH0xkwhYMmxRXrDtT0ZDiOD7j0B8HmhmWgTa1M4pgCebVhdtjMxx0qZh8OaP1SjaxMYxUVF84=,iv:IMxUybCHO04j0TXVWlMrTZFIHMErZVYqmD5kO2IhyKo=,tag:V6Yy46JlXsg5p+rToHX8ZA==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.13.3
