apiVersion: v1
kind: Secret
metadata:
    name: cluster-vars-prod
    namespace: flux-system
stringData:
    DOMAIN: ENC[AES256_GCM,data:4SWJxyyiv9dG,iv:f4Ew+u0LY7IV6Jy/qn+ZbqcGwbZsAheeP2VpHD8SEbM=,tag:YRcZ+M6xduE9U1D8dlYArQ==,type:str]
    DOMAIN2: ENC[AES256_GCM,data:DObhUFCYlxNczg==,iv:N4nkF1Bohj0Uph7ftHUD90gRkp0bPx83c0aQpaN3D6Y=,tag:RLYH2YHMtUkUsVDlI/6cXA==,type:str]
    GITEA_DOMAIN: ENC[AES256_GCM,data:+2SCDOv3fs1spNGcrg==,iv:DVAYFPWnM7fTyg5tgEFVnVxO00C6fb2GMzBTJgeQuT8=,tag:RO4CzwMCiNHDOn1dKQ8wzA==,type:str]
    AUTHELIA_DOMAIN: ENC[AES256_GCM,data:+CkeoHdG5qxEZWhZ3Y4=,iv:M4pL/iZRjIlxbsSNTnutQ1qEUPG0qHviJO5DkoG/H3o=,tag:f4GQSORrcR6jlWF8XT31Ug==,type:str]
    TRAEFIK_DOMAIN: ENC[AES256_GCM,data:q5CWKoylk9yAsYv/NlmxYW4=,iv:1VnT7tEwGZiPzWXFJXjAaZNFsXG35KdLhi00LqMGjmk=,tag:BOJPtPa5PX7vqmo7CjCDmg==,type:str]
    LEMMA_DOMAIN: ENC[AES256_GCM,data:giWjEOvuXAADm7vBdI/u,iv:61Re/87F+bWDF69hvmbyPwhrrS5KrW2gVWF7X5nCLbc=,tag:poZM9jXtaUHK/MBdY+X1iA==,type:str]
    GHOST_DOMAIN: ENC[AES256_GCM,data:lZMm9WUnskZczxX4NF0cWg==,iv:G6wj108xeVkRXasEp4QpcM9JK/sHRT61FHryXCId6Mo=,tag:czHHmYHlYpR3+C3KT4zgVg==,type:str]
    K8S_DASHBOARD_DOMAIN: ENC[AES256_GCM,data:GSVOBJrcAkU7DvIfWA==,iv:7luVGjNe+em+ivz9cQiGPjJXC9ol/cOrpfGV96ySaog=,tag:0WVrR2evmi3ovEJFa1Az0Q==,type:str]
    LETSENCRYPT_EMAIL: ENC[AES256_GCM,data:Du49Fb6x2/NYP3i4RWbvJstgGuTwE+4=,iv:TFo3AP4tS4PcrRV1ULeuZuiO70EOJKTerNQ6g1KRdlU=,tag:FgYDLI4FD+VBGwkY9AiNmg==,type:str]
    GITEA_ADMIN_EMAIL: ENC[AES256_GCM,data:pIy8Ti7uBQOt0rLi0v3Ykdk=,iv:7/Gbkn71yqk+TSwj8YS5ENhxeTFdvepBApLuxxkEkM0=,tag:2DG7aHgNO4VhGTTS7870uQ==,type:str]
    GHOST_ADMIN_EMAIL: ENC[AES256_GCM,data:w8y5OsjdcSmPQo3KICTwh3k=,iv:Wr+hZUvRa7NYPrLbEvqdI1mivJ9YWk2x6Sw+M85fUY4=,tag:abcTL9AcEXr0ji7mV8bcew==,type:str]
    LLAMACTL_DOMAIN: ENC[AES256_GCM,data:qPY7AqXqt3uOTC8ZQN7XUYZ1,iv:PPAiSuDo36HMCakzmuVQTRuH96DpMUg5vT+645cSnCQ=,tag:fVDZvQk3rys2C3cX0313jw==,type:str]
    LLAMACTL_TAILNET_FQDN: ENC[AES256_GCM,data:ZzbGSpMM9WSg+T2VNqG5wgmKpbF+CWMkMn6xjKA=,iv:KtFq1GDSKSk6swgGHH9sl8SrWQjIwAy/xazS7YGj4B4=,tag:F/Rg/F+VFyTKDnItBLSBkg==,type:str]
    LLAMACTL_INTERNAL_PORT: ENC[AES256_GCM,data:Y7o8AA==,iv:shZvcXJ8esfDNyhiTNiiq3hDkFsgJY29ON6jJQaTXY4=,tag:Au5NBVGPL7/+ZUZEVPcJuA==,type:str]
    CHATUI_DOMAIN: ENC[AES256_GCM,data:A26N7dtrtVtFR+bXf153Vlk9ljI=,iv:h83Qa7IgZJ6UH727W8ygDkZmKh6KxzdRARtCYmn5Cl0=,tag:+DjShvjpb+KMZiTY0TwpRw==,type:str]
    CHATUI_TAILNET_FQDN: ENC[AES256_GCM,data:ejLFj6/+yZSyPld48YfwEB9JsbAiL7ajGQBbMNU=,iv:t5JYr1JiJwwmlKN7OGcKdRzuliaVmffzqw14hUb485Q=,tag:0fEt+ad9uMom+BNRdPLLiA==,type:str]
    CHATUI_INTERNAL_PORT: ENC[AES256_GCM,data:7+SjDQ==,iv:RqG91IpYNpd0v5gOycEA+YdKQ4fz/R7z8J0QbqEoQMI=,tag:GJovb5dRUC4v+u/Nrt9S8w==,type:str]
sops:
    age:
        - recipient: age1jk99rtxq3ep2xj2w886cchddf7jypqpwkr3dszg5dzq93gn8cy9qyc786m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoT0tBZGIwUTNGVkxISTlC
            MTFtbU1yZ1hYMm14WnZ1Wi8zR0NXN3o4TVU4CmFXb1lNSmpsemJTRnpHU3IzbGlF
            T243MlgrOCtrRWVTeVdReFgxcXhWUXcKLS0tIFVLeCszbW1nWDhmQkFGejA2Vlpu
            US83LzlsbXVDdGlmN2FZL08vSGNjU2cKGToW3xmXjMHmux3APfIRz/uOeoDG9qD7
            25Su9PJfXNmE10D+wwA2ucYlLN7gP93yiDUHzKt/tgKorTBp4sriJg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-31T20:29:01Z"
    mac: ENC[AES256_GCM,data:FjQtSKbAGAiUJDjkJOAafLc9ZjH9XxoG1kd1Da8hqF/R4hyU3vAn6zSsAgvt1ae4xrtLOvyaT4JSNoIJyuOljA/i5ZyjtG3PT375uSTTn8q8fZjzwOhwhKKYpZAmKX9bvUeKPsfk7nQWt5aox0b81TH7726Z1ZtOD5h1O2LUtV4=,iv:f6SJp5uSqbPqNCmHwFcTznvJFoAy6T6xkIHKp0hHhJ0=,tag:Q/uweS39LEFheN2Pwt9hFg==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.10.2
