apiVersion: v1
kind: Secret
metadata:
    name: cluster-vars-prod
    namespace: flux-system
stringData:
    #ENC[AES256_GCM,data:jEJjaRANgPHiRh7KHwZa+w==,iv:1NsEQF4FQW0aUw0zEJRJEhbatH8+g4V0gX/B8IJSh44=,tag:pP1LorJabxpWWJAMJEpdnQ==,type:comment]
    DOMAIN: ENC[AES256_GCM,data:b3I05Uyz2ylT,iv:FHAeS/Fx3ndHeVI6Is6UQeexeFKZDizy1klx2TzQzmk=,tag:PAOIW23gTybc5VcXxvHyUQ==,type:str]
    DOMAIN2: ENC[AES256_GCM,data:DGMBgTEJzDlJzQ==,iv:cYUmZDOHlq0FifY2GK69W02UgGGTaNS9wpDHpCLEPYM=,tag:iVpe5yUZ8d4QOTcf8jvMDA==,type:str]
    #ENC[AES256_GCM,data:W3NvubqIbnaAJ2FSbllLlg==,iv:RHfo8KOj5QQ/c1/hbi2Pkm/OHGLFtyv7moXIAe0iCAU=,tag:oShgZbEYM20e6FWg7XMfJw==,type:comment]
    GITEA_DOMAIN: ENC[AES256_GCM,data:jXXIrelOjIUZQljQwg==,iv:7+YfxiypoI+2dCudQ+hiSXlyfymhcjIgXLkpWJdCOhU=,tag:M8QSzvW/1FZ+N33cg2Pn7w==,type:str]
    AUTHELIA_DOMAIN: ENC[AES256_GCM,data:NXBjRk3WZmUs6NCCFxE=,iv:pXFUMQnxAlxFPw6YIo3eplp+SkmqklQ5fcap+UNGTXk=,tag:7aWiOzmjILQcfTsztWCL8Q==,type:str]
    TRAEFIK_DOMAIN: ENC[AES256_GCM,data:A7s1vRVl8mBdro67TshSQuk=,iv:28BkG+UFGStAdwp+LgHdP0ex3dw++pOAvwZjRW8zHzo=,tag:s8fR32/GckIXz1EIUEgtDg==,type:str]
    LEMMA_DOMAIN: ENC[AES256_GCM,data:hk2vgd8ffZ9JDC5GlOEu,iv:bDLv/l/e6qTLOwtozo5bQxX66jOY6B+SWccGQtQtYfg=,tag:RMd/yavng9FVfMXBkesUtg==,type:str]
    GHOST_DOMAIN: ENC[AES256_GCM,data:3jUrnHm4D8kUAXSJZVT/vA==,iv:EuabeBPdol70cJRDkYrquqI+mypn+aDiRMtyIMX9cpo=,tag:t88hfZ2kMB6BApbts6vuJw==,type:str]
    K8S_DASHBOARD_DOMAIN: ENC[AES256_GCM,data:07J9UcJz+YP0qxdFsQ==,iv:poIAbkatlCuD6yCBGJ4tlXyXpUy7LvefXuVyL5FzDQw=,tag:RnildmtCM1beAzFhSGbMmQ==,type:str]
    #ENC[AES256_GCM,data:lMSidLVbf0hPokelTYzFUQoH+qk=,iv:fWowEXM4ZJdC9NuU4uzEJeVlSAeFoohCYtLxpmk5gUI=,tag:nIiUZ3XpfAzaNNrLiQuAog==,type:comment]
    LETSENCRYPT_EMAIL: ENC[AES256_GCM,data:zVht2eDJv36mCoWjrOg0wlNLtEN/Z6w=,iv:2G6D1KK0JzE3SRXr6ksbHT1alnB/SaaRUNoLqXOpA/E=,tag:Ryqsb6NL+HZmQFRjgQ/Ndg==,type:str]
    GITEA_ADMIN_EMAIL: ENC[AES256_GCM,data:4SuFQ7hufiWwU+OBWt1dVW8=,iv:Py6rsfwa5cgTzF3+eqXW4NGjiU0jNDMCOMtddL+S8Tg=,tag:XpQ3opLvWuYyMeJ0RB5suA==,type:str]
    GHOST_ADMIN_EMAIL: ENC[AES256_GCM,data:svoX2F6Uhcu/H5VN7fbuXYs=,iv:SoDStfQzETcYKtph/wlLhVTCB2mXEnRaR6tzL1VQFPI=,tag:cG4PHBcRNQ5BeycWGiYTZw==,type:str]
    #ENC[AES256_GCM,data:nNV4XIi4Dipy38DGUzcwUtyKF6R4cp8IwFF7oLoSaRNn,iv:wWRpHOh6GjH7RuGVOEwx6ENBWU3bbn5aAdAtPzRwDBQ=,tag:L45wY9vWsVGQeKj3i3D8Sw==,type:comment]
    LLAMACTL_DOMAIN: ENC[AES256_GCM,data:H7d7scTGLCwZzI/7DtV8OVTN,iv:Htb558G5MLj2+d0V1zOqK3k5SQBtGT+IQ9E0hpTjA80=,tag:1/H5a6Bm76xhn5CMqcxZIQ==,type:str]
    LLAMACTL_TAILNET_FQDN: ENC[AES256_GCM,data:a8VW7Jzu4X0a2uZEAJU5+vbQvqDlmQN2oTAoqwo=,iv:mX0E6VLmDt0pnlaQBktxeiJadpt/IqtbdaPCrWrzU+Y=,tag:YATnhjM9h0tISSX/YVM9gw==,type:str]
    LLAMACTL_INTERNAL_PORT: ENC[AES256_GCM,data:vu6PMA==,iv:0BpY+YRvCkHrNIJqfIKfqHVRqHSjUhmM5qGR5suL/Ec=,tag:VgtHePh1M6bAGl+562Baag==,type:str]
    CHATUI_DOMAIN: ENC[AES256_GCM,data:pSjvRHFhLP8M2LBiTDI=,iv:yBZCXjUOiXBJMblGuGtom4inoWmbpNeH+bb6WjuuAqs=,tag:SLTGon3qmUTC8b3M+SupOw==,type:str]
    CHATUI_TAILNET_FQDN: ENC[AES256_GCM,data:RdSAjz3FmqFVWoRbii4+s+wyTqKrxzM0T+720Ao=,iv:NnipwX4sN8VP/oZOtjU9konnjM07l3ZGU3yLRjfTWsM=,tag:BILlJsg+KooCW5FNZmc2iQ==,type:str]
    CHATUI_INTERNAL_PORT: ENC[AES256_GCM,data:Iik80w==,iv:NaHV/HhjFFo3OIP5jGQe3ihWyQ22gk9R8Tzg45Nk4GQ=,tag:a2zPIey7W/JascEZHN2UMw==,type:str]
    NETDATA_DOMAIN: ENC[AES256_GCM,data:n6hZnvvGg72TAGhd7A+k8oM=,iv:pUins4eDic0zk0yrKpvqnQhYa56hf3GhzhG0OhUx2LM=,tag:SZk4zOaKu0W4gt3HOLcRlA==,type:str]
    NETDATA_TAILNET_FQDN: ENC[AES256_GCM,data:p+EIQD6rXSGpFZ3x7KuXnavQ2e+mpvOEBe69EWw=,iv:ExlnEEd85ePSmgiW0d10KyYfGUy9Xwum9c0GYqAnLDw=,tag:auXMvCur61iUGgH1odALLg==,type:str]
    NETDATA_INTERNAL_PORT: ENC[AES256_GCM,data:Bo3LJII=,iv:R+s2QsSrRvBg89qLIdjxguBXMYUKfR4RmTRqNhFf/Is=,tag:WqAgdq9oeODq9/IoNX8ohw==,type:str]
    MCPO_DOMAIN: ENC[AES256_GCM,data:oWhY/YCrdKQ8TVglk1s=,iv:iMh8HO1uwPlXraD05InDiwuf3M1NjQQ1kcDPfn87+o0=,tag:CF9AaBytOattk3kGczQkNA==,type:str]
    MCPO_TAILNET_FQDN: ENC[AES256_GCM,data:1K74eWmR1o0UmHM40S09uaGPKUkOAjp3b/djR10=,iv:9sU19yRG4z7kA2RpkKbJdJScTRiJxeCuWv1v+p3UUSE=,tag:MwBgmP+pdsqTkggpa49rqQ==,type:str]
    MCPO_INTERNAL_PORT: ENC[AES256_GCM,data:q+ue4Zc=,iv:ry34C7rQLF1W6rJzaoNPu2lR9BC3gkYBSCEjnGlmXcA=,tag:ATkqSfrvpe6obdSaT+oFSg==,type:str]
    HOMELAB_DOMAIN: ENC[AES256_GCM,data:OjxPknnP7j81puPokaa1g2w=,iv:/m+vrr5BpwVtqn9W2S125Ncv4Sr4KFXxbt+yfFcDwUc=,tag:7+lZNBwCktsAOyKnHIMUAQ==,type:str]
    HOMELAB_TAILNET_FQDN: ENC[AES256_GCM,data:tsMGXpZLJvtZs2H5ogIhnTKiKXYw84lZDknjbr0=,iv:CLvXwbgYLt4kVsfbSPdkK2BUQ8BFoRoOuHJ67FtpW94=,tag:hb/pIucHBRx3Mex8J2qUXw==,type:str]
    HOMELAB_INTERNAL_PORT: ENC[AES256_GCM,data:4soWug==,iv:icKAXdg+WRW1qPeOIg5W8NziX0fNWKbd69+hD0dhDhQ=,tag:xBLsbOJk7bogg+/c+RZ1Pg==,type:str]
sops:
    age:
        - recipient: age1jk99rtxq3ep2xj2w886cchddf7jypqpwkr3dszg5dzq93gn8cy9qyc786m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByWkUvWkNVT3BmbnBZYW5n
            c0VCNEU5Z211MVhidGYzblVmdGZmZWhCY2lNCnhucENVZTBESGlPR2ticzgxMXlm
            MmxoZUF2eTdyNnpRRzBWaE1IUExBSUUKLS0tIFp0ZkUxeGU3bG50OGlBUUNid01q
            N3huZW5ZcjhFdHc2d3pzSVAvb0I3RGsKP2Vmam21JhexxTjNWjsgmnvywy/9ZvpZ
            YsirKnhW08O9iBwyVjW2qs/Q554ab/IrzFBLmmqZYMflCMYGnZwNFA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-17T19:14:22Z"
    mac: ENC[AES256_GCM,data:Z0ZgkVoKC70yuo23YrcfCXE1hEmsrQqrEo9pLlmCQPTS8nrEL4PS88hz36z3bTxmsoYs/5iLvcNt0OOfy05RJ7INie0g6c04BDIZoPz3PvD24/IQUm9dLtj20qUYvY89iV3vieypHgOkLgepvPv8vf3e2igOJB2Q3gNw80q4TpI=,iv:vdVnRYw6We84gyK3+DKwSEFN0TpV6gTeYtfX6YqDO88=,tag:CWa3VskWRSp5tLUcHeciHg==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.11.0
