apiVersion: batch/v1
kind: Job
metadata:
  name: gitea-project-migration-inspect
  namespace: gitea
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: inspect
          image: postgres:17-alpine
          env:
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: gitea-postgresql
                  key: password
            - name: PGHOST
              value: gitea-postgresql
            - name: PGUSER
              value: gitea
            - name: PGDATABASE
              value: gitea
          command:
            - /bin/sh
            - -c
            - |
              set -e
              echo "=== Gitea Project Migration Inspection ==="

              echo ""
              echo "--- User: mathis ---"
              psql -c "SELECT id, name, login FROM \"user\" WHERE lower(login) = 'mathis';"

              REPO_ID=$(psql -Atc "SELECT r.id FROM repository r JOIN \"user\" u ON u.id = r.owner_id WHERE lower(u.login) = 'mathis' AND lower(r.name) = 'projects';")
              if [ -z "$REPO_ID" ]; then
                echo "ERROR: Repository Mathis/Projects not found"
                exit 1
              fi

              echo ""
              echo "--- Repository Mathis/Projects (id=$REPO_ID) ---"
              psql -c "SELECT id, name, owner_id, is_private FROM repository WHERE id = $REPO_ID;"

              PROJECT_ID=$(psql -Atc "SELECT id FROM project WHERE repo_id = $REPO_ID AND title = 'Projects';")
              if [ -z "$PROJECT_ID" ]; then
                echo "ERROR: Project 'Projects' not found in repo id=$REPO_ID"
                exit 1
              fi

              echo ""
              echo "--- Project (id=$PROJECT_ID) ---"
              psql -c "SELECT id, title, description, creator_id, repo_id, type, is_closed, created_unix, updated_unix FROM project WHERE id = $PROJECT_ID;"

              echo ""
              echo "--- project_issue table schema ---"
              psql -c "SELECT column_name, data_type FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'project_issue' ORDER BY ordinal_position;"

              echo ""
              echo "--- Board/column table detection ---"
              HAS_BOARD=$(psql -Atc "SELECT COUNT(*) FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'project_board';")
              if [ "$HAS_BOARD" = "1" ]; then
                BOARD_TABLE="project_board"
              else
                BOARD_TABLE="project_column"
              fi
              echo "Using table: $BOARD_TABLE"

              echo ""
              echo "--- $BOARD_TABLE schema ---"
              psql -c "SELECT column_name, data_type FROM information_schema.columns WHERE table_schema = 'public' AND table_name = '$BOARD_TABLE' ORDER BY ordinal_position;"

              echo ""
              echo "--- Project boards/columns ---"
              psql -c "SELECT * FROM $BOARD_TABLE WHERE project_id = $PROJECT_ID ORDER BY sorting;"

              echo ""
              echo "--- project_issue board/column FK column ---"
              HAS_BOARD_COL=$(psql -Atc "SELECT COUNT(*) FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'project_issue' AND column_name = 'project_board_id';")
              if [ "$HAS_BOARD_COL" = "1" ]; then
                BOARD_COL="project_board_id"
              else
                BOARD_COL="project_column_id"
              fi
              echo "Using column: $BOARD_COL"

              echo ""
              echo "--- Project issues with board/column assignment ---"
              psql -c "SELECT pi.issue_id, i.index AS issue_number, i.title AS issue_title, i.is_closed, b.title AS board_title, b.id AS board_id FROM project_issue pi JOIN issue i ON i.id = pi.issue_id LEFT JOIN $BOARD_TABLE b ON b.id = pi.$BOARD_COL WHERE pi.project_id = $PROJECT_ID ORDER BY b.sorting NULLS LAST, i.index;"

              echo ""
              echo "--- Summary ---"
              psql -c "SELECT COUNT(*) AS total_issues FROM project_issue WHERE project_id = $PROJECT_ID;"
              psql -c "SELECT COUNT(*) AS total_columns FROM $BOARD_TABLE WHERE project_id = $PROJECT_ID;"

              echo ""
              echo "=== Inspection Complete ==="
