# /apps/prod/gitea/release.yaml
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gitea
  namespace: gitea
spec:
  interval: 1h
  chart:
    spec:
      chart: gitea
      version: 11.0.0
      sourceRef:
        kind: HelmRepository
        name: gitea
        namespace: gitea
      interval: 1h
  valuesFrom:
    - kind: ConfigMap
      name: gitea-prod-values