apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lute-data
  namespace: lute
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: retain-local-path
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lute-backup
  namespace: lute
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: retain-local-path
  resources:
    requests:
      storage: 2Gi
