apiVersion: v1
kind: Service
metadata:
  name: ghost
  namespace: ghost
  labels:
    app: ghost
spec:
  selector:
    app: ghost
  ports:
  - port: 80
    targetPort: 2368
    name: http
  type: ClusterIP