---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: crowdsec
  namespace: crowdsec
spec:
  interval: 10m
  chart:
    spec:
      chart: crowdsec
      version: 0.22.0
      sourceRef:
        kind: HelmRepository
        name: crowdsec-helm-repo
      interval: 10m
  valuesFrom:
    - kind: ConfigMap
      name: crowdsec-prod-values
