# /infrastructure/controllers/traefik/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - repository.yaml
  - release.yaml
  - crds.yaml

configMapGenerator:
  - name: traefik-prod-values
    namespace: traefik
    files:
      - values.yaml
