# /infrastructure/controllers/traefik/release.yaml
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 10m
  chart:
    spec:
      chart: traefik
      version: 34.3.0
      sourceRef:
        kind: HelmRepository
        name: traefik-helm-repo
      interval: 10m
  valuesFrom:
    - kind: ConfigMap
      name: traefik-prod-values