apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: auth

resources:
  - release.yaml
  - ingress.yaml
  - forward-auth-middleware.yaml

configMapGenerator:
  - name: authelia-prod-values
    namespace: auth
    files:
      - values.yaml

patchesStrategicMerge:
  - release.yaml