# /apps/prod/headlamp/release.yaml
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: headlamp
  namespace: headlamp
spec:
  interval: 12h
  chart:
    spec:
      chart: headlamp
      version: 0.40.0
      sourceRef:
        kind: HelmRepository
        name: headlamp
        namespace: headlamp
      interval: 12h
