apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gitea
  namespace: gitea
spec:
  interval: 1h
  chart:
    spec:
      chart: gitea
      version: 10.2.0
      sourceRef:
        kind: HelmRepository
        name: gitea
        namespace: gitea
      interval: 1h