# /apps/prod/authelia/release.yaml
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authelia
  namespace: auth
spec:
  interval: 12h
  chart:
    spec:
      chart: authelia
      version: 0.10.32
      sourceRef:
        kind: HelmRepository
        name: authelia
        namespace: auth
      interval: 12h
  valuesFrom:
    - kind: ConfigMap
      name: authelia-prod-values