# /apps/prod/authelia/values.yaml
configMap:
  authentication_backend:
    file:
      enabled: true
      path: /users/users_database.yaml
      password:
        algorithm: argon2
    ldap:
      enabled: false
  access_control:
    rules:
      - domain: '*.${MAIN_DOMAIN}'
        policy: two_factor
  server:
    endpoints:
      automatic_authz_implementations: ['ForwardAuth', 'AuthRequest']
  session:
    redis:
      enabled: false
    cookies:
      - domain: '${MAIN_DOMAIN}'
        subdomain: 'auth'
        name: 'authelia_session'
  storage:
    local:
      enabled: true
      path: /config/db.sqlite3
    postgres:
      enabled: false
  notifier:
    smtp:
      enabled: false
    filesystem:
      enabled: true
  identity_providers:
    oidc:
      enabled: true
      jwks:
        - key_id: 'rs256-1'
          algorithm: 'RS256'
          use: 'sig'
          key:
            path: '/secrets/authelia-oidc/rs256.pem'
      claims_policies:
        llamactl:
          id_token: ['name', 'email', 'email_verified']  
      clients:
        - client_id: 'forgejo'
          client_name: 'Forgejo'
          client_secret:
            path: '/secrets/authelia-oidc/forgejo.client'
          redirect_uris:
            - 'https://${FORGEJO_DOMAIN}/user/oauth2/Authelia/callback'
        - client_id: 'vikunja'
          client_name: 'Vikunja'
          client_secret:
            path: '/secrets/authelia-oidc/vikunja.client'
          redirect_uris:
            - 'https://${VIKUNJA_DOMAIN}/auth/openid/authelia'
        - client_id: 'llamactl'
          client_name: 'Llamactl'
          client_secret:
            path: '/secrets/authelia-oidc/llamactl.client'
          redirect_uris:
            - 'https://${LLAMACTL_DOMAIN}/api/v1/auth/oidc/callback'
          scopes: ['openid', 'profile', 'email']
          claims_policy: 'llamactl'

secret:
  additionalSecrets:
    authelia-oidc: {}

pod:
  extraVolumeMounts:
  - name: authelia-users-vol
    mountPath: /users
  extraVolumes:
  - name: authelia-users-vol
    secret:
      secretName: authelia-users-secret

ingress:
  enabled: true
  traefikCRD:
    enabled: true
    matchOverride: Host(`${AUTHELIA_DOMAIN}`)
    entryPoints:
      - "websecure"

persistence:
  enabled: true
  storageClass: retain-local-path
  size: 1Gi
  accessModes:
    - ReadWriteOnce
