apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: authelia
  namespace: auth
spec:
  interval: 12h
  chart:
    spec:
      chart: authelia
      version: 0.8.58
      sourceRef:
        kind: HelmRepository
        name: authelia
        namespace: auth
      interval: 12h