# /infrastructure/base/authelia/repository.yaml
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: authelia
  namespace: auth
spec:
  interval: 24h
  url: https://charts.authelia.com
