apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: lemma
  namespace: lemma
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`${LEMMA_DOMAIN}`)
      kind: Rule
      services:
        - name: lemma-http
          port: 80
