apiVersion: v1
kind: Service
metadata:
  name: llamactl-proxy
  namespace: llamactl
spec:
  type: ExternalName
  externalName: ${LLAMACTL_INTERNAL_IP}
  ports:
  - port: 80
    targetPort: ${LLAMACTL_INTERNAL_PORT}
    name: http