apiVersion: v1
kind: Service
metadata:
  name: llamactl-proxy
  namespace: llamactl
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: ${LLAMACTL_INTERNAL_PORT}
    name: http
  selector: {}