apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: kube-system
spec:
  interval: 10m
  chart:
    spec:
      chart: traefik
      version: 28.2.0
      sourceRef:
        kind: HelmRepository
        name: traefik
      interval: 10m
  values:
    replicaCount: 2