# /infrastructure/core/local-path-provisioner.yaml
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: local-path-provisioner
  namespace: flux-system
spec:
  interval: 30m
  url: https://github.com/rancher/local-path-provisioner.git
  ref:
    tag: v0.0.32
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: local-path-provisioner
  namespace: flux-system
spec:
  interval: 15m
  prune: true
  sourceRef:
    kind: GitRepository
    name: local-path-provisioner
    namespace: flux-system
  path: ./deploy
  targetNamespace: local-path-storage
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: local-path-provisioner
      namespace: local-path-storage