# /infrastructure/controllers/velero/release.yaml
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: velero
  namespace: velero
spec:
  interval: 1h
  chart:
    spec:
      chart: velero
      version: 8.3.0
      sourceRef:
        kind: HelmRepository
        name: velero-helm-repo
        namespace: velero
  values:
    snapshotsEnabled: false
    deployNodeAgent: true
    configuration:
      backupStorageLocation:
      - name: scaleway
        provider: velero.io/aws
        default: true
        bucket: ${VELERO_BUCKET}
        config:
          region: nl-ams
          s3Url: https://s3.nl-ams.scw.cloud

      defaultVolumesToFsBackup: true
      
    schedules:
      daily-backup:
        schedule: "0 2 * * *"
        template:
          includedNamespaces:
            - forgejo
          storageLocation: default
          ttl: "168h"
          includedResources:
            - persistentvolumeclaims
            - persistentvolumes
          labels:
            type: scheduled
            period: daily

    credentials:
      existingSecret: velero-s3-credentials

    initContainers:
      - name: velero-plugin-for-aws
        image: velero/velero-plugin-for-aws:v1.11.1
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - mountPath: /target
            name: plugins