# /infrastructure/controllers/velero/release.yaml
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: velero
  namespace: velero
spec:
  interval: 1h
  chart:
    spec:
      chart: velero
      version: 8.2.0
      sourceRef:
        kind: HelmRepository
        name: velero-helm-repo
        namespace: velero
  values:
    snapshotsEnabled: false
    deployNodeAgent: true
    configuration:
      backupStorageLocation:
      - name: scaleway
        provider: aws
        default: true
        bucket: ${VELERO_BUCKET}
        credential:
          key: cloud
          name: velero-s3-credentials
        config:
          region: nl-ams
          s3Url: https://s3.nl-ams.scw.cloud

      defaultVolumesToFsBackup: true
      
    # Backup schedules
    schedules:
      daily-backup:
        schedule: "0 2 * * *"  # Every day at 2 AM
        template:
          includedNamespaces:
            - forgejo
          storageLocation: default
          ttl: "168h"  # Keep backups for 1 week
          includedResources:
            - persistentvolumeclaims
            - persistentvolumes
          labels:
            type: scheduled
            period: daily

    credentials:
      existingSecret: velero-s3-credentials

    resources:
      requests:
        cpu: 200m
        memory: 256Mi
      limits:
        cpu: 1000m
        memory: 512Mi

    nodeAgent:
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 500m
          memory: 256Mi

    initContainers:
      - name: velero-plugin-for-aws
        image: velero/velero-plugin-for-aws:v1.11.1
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - mountPath: /target
            name: plugins