apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: velero
  namespace: velero
spec:
  interval: 1h
  chart:
    spec:
      chart: velero
      version: 10.1.0
      sourceRef:
        kind: HelmRepository
        name: velero-helm-repo
        namespace: velero
  valuesFrom:
    - kind: ConfigMap
      name: velero-prod-values
      valuesKey: values.yaml
