# /apps/base/forgejo/repository.yaml
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: forgejo
  namespace: forgejo
spec:
  interval: 1h
  url: https://code.forgejo.org/forgejo-helm/forgejo