# /infrastructure/prod/traefik/certificate.yaml
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-nmsny-dev
  namespace: traefik
spec:
  secretName: wildcard-nmsny-dev-tls
  dnsNames:
    - "nmsny.dev"
    - "*.nmsny.dev"
  issuerRef:
    name: cloudflare-prod
    kind: Issuer