apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/traefik
  - traefik-values.yaml

configMapGenerator:
  - name: traefik-prod-values
    namespace: traefik
    files:
      - values.yaml