deployment:
  additionalVolumes:
  - name: access-log
    hostPath:
      path:  /var/log/traefik/
additionalVolumeMounts:
- name: access-log
  mountPath: /var/log/traefik/
logs:
  access:
    enabled: true
    filePath: /var/log/traefik/access.log
ingressRoute:
  dashboard:
    enabled: true
    matchRule: Host(`traefik.namesny.com`)
    entryPoints: ["websecure"]
    middlewares:
      - name: "auth-authelia@kubernetescrd"
providers:
  kubernetesCRD:
    allowCrossNamespace: true
persistence:
  enabled: true
  storageClass: retain-local-path
ports:
  websecure:
    tls:
      enabled: true
  web:
    redirectTo:
      port: websecure
service:
  spec:
    externalTrafficPolicy: Local
