apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: k8up
  namespace: k8up-system
spec:
  interval: 1h
  chart:
    spec:
      chart: k8up
      version: 4.8.6
      sourceRef:
        kind: HelmRepository
        name: k8up
        namespace: k8up-system
      interval: 1h
  values:
    replicaCount: 1
