#ENC[AES256_GCM,data:cu+9wnuR6pqcsIbg5yBclb5u5dgXlHiPOaPltjTQDWpW3venFx8hLzxfNChMNOHEwChhb9Y=,iv:TqzQq1wOkaGAzgou/rqQ1ihKy7ujZ7sy72oCM0L1HUs=,tag:iPgFZQWdROAywGL9QFAtFg==,type:comment]
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token-secret
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:X0TQssUQDhuIkKJ2qFrm/U5ElvelX7mJ9tJnE8Xu4ubYQanddjL4Kg==,iv:fo75MvhvXZjAGjYMKqnlSK2gIMqt7LNznpri/PlLYR4=,tag:9P3msuVx1JVkCQLni995tg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jk99rtxq3ep2xj2w886cchddf7jypqpwkr3dszg5dzq93gn8cy9qyc786m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZbW9Kalg5Mk5ZQzF3RGdv
            R01nUWJRMDhEWUNMMkxFRVRHa3JRZlh1VFJZCmI5VTc4WEt3WFFlUXV1bENsdDlh
            c3JTQmJpUXVsT3lzd01OK0RCYU1kQXMKLS0tIHROY3UwTnNFRTE2NWdMWTJPMzRO
            Um0xQjRtcjFtTWU3WG9sTWxtOWtUTDgKz2lxIK3iXlUuaCPKxrh+iRv7jN7c3Tqc
            TNXJvStXa5nCKU5FICHtWNfL6V1E8mojXXgCn5I41fvd8Vl65JKPcw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-18T12:57:59Z"
    mac: ENC[AES256_GCM,data:LiZIXu67ZIxfROc9NIlZRniqBRlUFYOUCKF+SKV6TPW2eVyN0VxgsTn5j1ltirJbV/BkfRcHI9ccnNO+hcWGnZtoIWomIo1puieXwI0uKBpDwp7qgkQoO8yr1VTQ0b7iqaM2EbjrPYO6LpxehMVoNGys1FzWjKRIQcP4Fu5zAfY=,iv:tW3uubNQ3gzjGiiMl8CgHcpeShkbqzpnSaXFWMwiEfM=,tag:eGCfHV00z+tBcTBiGTDGjw==,type:str]
    pgp: []
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.9.0
---
apiVersion: cert-manager.io/v1
kind: Secret
metadata:
    name: cloudflare-api-token-secret-domain2
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:z80b0SFZWgXV0Jyk5Gtv7pqdb+hR5OjODwn853/DLmksj622TlrZhw==,iv:BlCv2/6p5mA9Bj757iBSHGXg8iEPgSp0TmtbJUixzDg=,tag:W8pmzZRySEZPMEluEei+yg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jk99rtxq3ep2xj2w886cchddf7jypqpwkr3dszg5dzq93gn8cy9qyc786m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZbW9Kalg5Mk5ZQzF3RGdv
            R01nUWJRMDhEWUNMMkxFRVRHa3JRZlh1VFJZCmI5VTc4WEt3WFFlUXV1bENsdDlh
            c3JTQmJpUXVsT3lzd01OK0RCYU1kQXMKLS0tIHROY3UwTnNFRTE2NWdMWTJPMzRO
            Um0xQjRtcjFtTWU3WG9sTWxtOWtUTDgKz2lxIK3iXlUuaCPKxrh+iRv7jN7c3Tqc
            TNXJvStXa5nCKU5FICHtWNfL6V1E8mojXXgCn5I41fvd8Vl65JKPcw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-18T12:57:59Z"
    mac: ENC[AES256_GCM,data:LiZIXu67ZIxfROc9NIlZRniqBRlUFYOUCKF+SKV6TPW2eVyN0VxgsTn5j1ltirJbV/BkfRcHI9ccnNO+hcWGnZtoIWomIo1puieXwI0uKBpDwp7qgkQoO8yr1VTQ0b7iqaM2EbjrPYO6LpxehMVoNGys1FzWjKRIQcP4Fu5zAfY=,iv:tW3uubNQ3gzjGiiMl8CgHcpeShkbqzpnSaXFWMwiEfM=,tag:eGCfHV00z+tBcTBiGTDGjw==,type:str]
    pgp: []
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.9.0
