apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ghost

resources:
  - ../../base/ghost
  - pvc.yaml
  - ingress.yaml

patchesStrategicMerge:
  - deployment-patch.yaml

configurations:
  - kustomizeconfig.yaml