apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ghost-content
  namespace: ghost
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: retain-local-path
  resources:
    requests:
      storage: 5Gi