apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ghost
  namespace: ghost
spec:
  interval: 1h
  chart:
    spec:
      chart: ghost
      version: "22.2.3"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: ghost
      interval: 1h
  valuesFrom:
    - kind: ConfigMap
      name: ghost-prod-values