#ENC[AES256_GCM,data:Crbqb/zmiprmDIRR5NDpnt3mWi3u0X2vS6zztsXQsuwHzSFN,iv:nmej4uPk86WEZwy7AcpxBEfBzDPGr/m+IKyWOXkEhcM=,tag:u6oalaUlU4NoKzQh0iQhgQ==,type:comment]
apiVersion: v1
kind: Secret
metadata:
    name: vikunja-oidc
    namespace: vikunja
stringData:
    clientsecret: ENC[AES256_GCM,data:oyUt5mT/VPltwD777ROPdrIuOZM8nCmO9smvo4YAlwOz8aT6Nsmqopn+EoQvuAEnFLpQA8Q+0QCZInFif//wQQ==,iv:b7oNA0LLHCe/ZXI2+buCDIKpj15JksJh5Bgq52G88z0=,tag:QtLalO9smhG+Ntdz6GcCMA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0YUVxTlZTa2JKaWczaEdV
            ZWozK0tiWElZM2pHaEpUcXRnUDNOVE5HcG5BCjJiY09KMGlielBhQm9CTVluS1RO
            SzdjVlplcmdZUEVSNlBMQlNEVzNybVUKLS0tICtyQWIvaGI1T0xtekdsUFYvOEd5
            Q016aDRneVZLWDltVXEyTFBBYnhIakkKEC9QFXNc6BGc3s2BrOpDfc3Tjq4CY9wJ
            xzYGgrrtVEJ7YOB4CMkjpQaYTLJf4KntdJ9gFkQ3Om/aEfmYHnMr+g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jk99rtxq3ep2xj2w886cchddf7jypqpwkr3dszg5dzq93gn8cy9qyc786m
    lastmodified: "2026-10-04T20:44:52Z"
    mac: ENC[AES256_GCM,data:V5916eijLlDHsEdCjYVboNNPVtzxZpPEpyOQhgsqDgBFkeJjZwgeKrgCJUYeHehfqdH5zkFjbYpzo8OE4hWc038pCs4v/GkyfcXu7Q5CxToz5a9YuTZ50HL9zvUTc6o8f9dAbfguspue9rYySCOtfRuZrIOWuQwzMVXpO8iglCw=,iv:tL+s70MZ5RAmCNFwAMP/crdymDxYZhthblH5x8rc4Gk=,tag:EuIz6ynFDU6ewr2V2wu0CA==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.13.3
