vikunja:
  persistence:
    data:
      storageClass: retain-local-path
    database:
      storageClass: retain-local-path
  ingress:
    main:
      enabled: false
  configMaps:
    config:
      enabled: true
      data:
        config.yml: |
          auth:
            openid:
              enabled: true
              providers:
                authelia:
                  name: Authelia
                  authurl: https://${AUTHELIA_DOMAIN}
                  clientid: vikunja
                  usernamefallback: true
                  emailfallback: true
  env:
    VIKUNJA_SERVICE_PUBLICURL: https://${VIKUNJA_DOMAIN}
    VIKUNJA_SERVICE_ENABLEREGISTRATION: false
    VIKUNJA_AUTH_OPENID_PROVIDERS_AUTHELIA_CLIENTSECRET:
      valueFrom:
        secretKeyRef:
          name: vikunja-oidc
          key: clientsecret